# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
#
# Stage 3 reference generator, CalTRACK/TOWT edition.
#
# STRUCTURE
# ---------
# Three parts, following the industry-standard shape for hourly load impact:
#
#   * The DERIVATION is the CalTRACK / OpenDSM Time-of-Week & Temperature (TOWT)
#     model form: a weighted least-squares regression of metered load on
#     time-of-week indicators and piecewise-linear temperature terms. Its
#     regressors are the CALENDAR and the WEATHER, both public, so the
#     coefficient map M = (X'X)^-1 X' is public and every derived quantity is a
#     PUBLIC LINEAR FUNCTIONAL of the household's private consumption series.
#     That is what makes it evaluable under CKKS as plaintext-matrix x ciphertext.
#         https://docs.caltrack.org/en/latest/methods.html
#         https://github.com/opendsm/opendsm      (Apache-2.0 reference impl)
#
#   * The LABEL is a MEASURED load impact. We simulate a
#     real demand-response event, compute the household's Customer Baseline Load
#     (10-in-10 style: same event hours averaged over the 10 most recent similar
#     weekdays), subtract the actual event load, and label the household eligible
#     if the measured reduction clears a kW threshold. The label is produced by
#     the measurement protocol applied to simulated behaviour.
#
#   * The MODEL is the utility's CONFIDENTIAL scoring layer: ridge logistic
#     regression over the six derived quantities. It is a plaintext operand held
#     by the server and never disclosed to the household.
#
# Outputs:
#   model/derivation.txt      PUBLIC. Six row vectors r_j (length 672). Derived
#                             from calendar + weather only. Feature_j = r_j . y.
#   model/model.txt           CONFIDENTIAL. The utility's six weights + bias +
#                             the in-circuit sigmoid domain/degree.
#   data/test_inputs.csv      400 held-out households, 672 hourly kWh each.
#   data/train_inputs.csv     first 100 training households (for inspection).
#   data/test_labels.csv      idx,y_true,reduction_kw (the measured answer key).
#
# HONEST LIMITATIONS (see docs/design-narrative.md):
#   - Synthetic weather and households; seeded, reproducible, not real AMI data.
#   - Reduced time-of-week basis (hour-of-day x weekday/weekend = 48 indicators)
#     rather than the full 168, because a 28-day baseline cannot identify 168.
#   - Cooling-side temperature bins only; the heating bins would be identically
#     zero over a summer baseline and rank-deficient against the TOW indicators.
#   - OLS rather than CalTRACK's calendar-month weighting: a 28-day window sits
#     inside one month, so every weight would be 1.0 anyway.
import numpy as np, os

SEED = 20260808
rng = np.random.default_rng(SEED)
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

DAYS = 28
HOURS = DAYS * 24                 # 672 slots -- the encrypted boundary vector
EVENT_HOURS = [17, 18, 19, 20]    # 5-9pm, four hourly intervals
MIDDAY_HOURS = [10, 11, 12, 13, 14, 15]
N_TRAIN, N_TEST = 3000, 400
CBL_DAYS = 10                     # 10-in-10 customer baseline
TEMP_KNOTS = [65.0, 75.0, 90.0]   # cooling-side CalTRACK breakpoints
DESIGN_TEMP = 95.0                # ex-ante design condition for the peak predictor
TARGET_BASE_RATE = 1.0 / 3.0
TOP_FRACTION = 0.20               # recruitment depth quality is reported at

hour_of = np.arange(HOURS) % 24
day_of = np.arange(HOURS) // 24
# day 0 is a Monday; 5,6 = Sat,Sun
is_weekend_day = ((np.arange(DAYS) % 7) >= 5)
is_weekend = is_weekend_day[day_of]


# ---- public covariates: weather ---------------------------------------------
def make_temperature(n_hours, rng, base=78.0):
    """Hourly dry-bulb temperature (F): seasonal drift + diurnal cycle + noise."""
    t = np.arange(n_hours)
    d, h = t // 24, t % 24
    seasonal = base + 5.0 * np.sin(2 * np.pi * (d - 4) / 55.0)
    diurnal = 11.0 * np.sin(2 * np.pi * (h - 9) / 24.0)
    return seasonal + diurnal + rng.normal(0, 2.0, n_hours)


TEMP = make_temperature(HOURS, rng)


def temp_basis(temp):
    """Piecewise-linear cooling terms at the CalTRACK breakpoints."""
    k = TEMP_KNOTS
    return np.column_stack([
        np.clip(temp - k[0], 0, k[1] - k[0]),   # 65-75 F
        np.clip(temp - k[1], 0, k[2] - k[1]),   # 75-90 F
        np.clip(temp - k[2], 0, None),          # >90 F
    ])


# ---- the TOWT design matrix (public: calendar + weather only) ---------------
def towt_design(temp, hour, weekend):
    """48 hour-of-day x day-type indicators + 3 cooling terms. No intercept."""
    n = len(temp)
    tow = np.zeros((n, 48))
    tow[np.arange(n), hour + 24 * weekend.astype(int)] = 1.0
    return np.column_stack([tow, temp_basis(temp)])


X = towt_design(TEMP, hour_of, is_weekend)
P = X.shape[1]
rank = np.linalg.matrix_rank(X)
assert rank == P, f"TOWT design matrix is rank-deficient: rank {rank} of {P} columns"
M = np.linalg.solve(X.T @ X, X.T)          # (P, HOURS) -- PUBLIC coefficient map


# ---- households --------------------------------------------------------------
def make_households(n, rng):
    """Draw household parameters. `willingness` is behavioural and deliberately
    invisible in the meter data -- it is the irreducible noise that caps how well
    any model fitted to the baseline period can predict event response."""
    return dict(
        base=rng.uniform(0.12, 0.45, n),            # always-on load
        morning=rng.uniform(0.2, 1.1, n),
        evening=rng.uniform(0.3, 2.2, n),
        midday=rng.uniform(0.0, 0.9, n),
        weekend_lift=rng.uniform(0.9, 1.6, n),      # more at home on weekends
        ac_slope=np.where(rng.uniform(size=n) < 0.25, 0.0,
                          rng.uniform(0.02, 0.30, n)),   # 25% have no cooling
        willingness=rng.beta(2.0, 2.5, n),          # fraction of AC load actually shed
    )


def ac_duty(hour):
    """Cooling load lags outdoor temperature; peaks late afternoon/evening."""
    return 0.35 + 0.65 * np.exp(-0.5 * ((hour - 17) / 4.0) ** 2)


def simulate_load(hh, temp, hour, weekend, rng):
    """Hourly kWh for each household over the given hours. Shape (n, len(temp))."""
    n = len(hh["base"])
    h, wk = hour[None, :], weekend[None, :].astype(float)
    lift = 1.0 + (hh["weekend_lift"][:, None] - 1.0) * wk
    morn = hh["morning"][:, None] * np.exp(-0.5 * ((h - 7.5 - 1.5 * wk) / 1.5) ** 2)
    eve = hh["evening"][:, None] * lift * np.exp(-0.5 * ((h - 19) / 2.0) ** 2)
    mid = hh["midday"][:, None] * lift * np.exp(-0.5 * ((h - 13) / 2.8) ** 2)
    cool = (hh["ac_slope"][:, None]
            * np.clip(temp[None, :] - 65.0, 0, None)
            * ac_duty(h))
    noise = rng.normal(0, 0.05, (n, len(temp)))
    return np.clip(hh["base"][:, None] + morn + eve + mid + cool + noise, 0.02, None)


# ---- the six derived quantities: each a PUBLIC linear functional r_j . y -----
def build_derivation_rows():
    """Return (names, R) with R of shape (6, HOURS). Feature_j(y) = R[j] . y."""
    names, rows = [], []

    # 1. cbl_peak -- the 10-in-10 Customer Baseline Load for the event window:
    #    the event hours averaged over the 10 most recent non-event weekdays.
    weekdays = [d for d in range(DAYS) if not is_weekend_day[d]]
    cbl_days = weekdays[-CBL_DAYS:]
    r = np.zeros(HOURS)
    for d in cbl_days:
        for h in EVENT_HOURS:
            r[d * 24 + h] = 1.0 / (len(cbl_days) * len(EVENT_HOURS))
    names.append("cbl_peak"); rows.append(r)

    # 2. cool_slope_hi -- the TOWT coefficient on the 75-90F cooling term.
    names.append("cool_slope_hi"); rows.append(M[48 + 1].copy())

    # 3. peak_towt_design -- TOWT-predicted event-window load at the design
    #    temperature (ex-ante conditions), averaged over the event hours.
    x_design = towt_design(np.full(len(EVENT_HOURS), DESIGN_TEMP),
                           np.array(EVENT_HOURS),
                           np.zeros(len(EVENT_HOURS), dtype=bool)).mean(axis=0)
    names.append("peak_towt_design"); rows.append(x_design @ M)

    # 4. daily_mean -- overall level (mean hourly kWh across the baseline).
    names.append("daily_mean"); rows.append(np.full(HOURS, 1.0 / HOURS))

    # 5. midday_mean -- daytime-occupancy proxy; daytime-heavy users shed less.
    r = np.zeros(HOURS)
    sel = np.isin(hour_of, MIDDAY_HOURS)
    r[sel] = 1.0 / sel.sum()
    names.append("midday_mean"); rows.append(r)

    # 6. weekend_evening_delta -- weekend minus weekday evening load.
    r = np.zeros(HOURS)
    we = np.isin(hour_of, EVENT_HOURS) & is_weekend
    wd = np.isin(hour_of, EVENT_HOURS) & ~is_weekend
    r[we] = 1.0 / we.sum(); r[wd] = -1.0 / wd.sum()
    names.append("weekend_evening_delta"); rows.append(r)

    return names, np.array(rows)


FEATURES, R = build_derivation_rows()


# ---- the measured label: simulate an event, measure against the CBL ----------
def measured_reduction(hh, Y, rng):
    """Run a DR event on a hot weekday and measure the reduction the way a
    settlement process would: CBL (from the baseline period) minus actual."""
    n = len(hh["base"])
    ev_hour = np.array(EVENT_HOURS)
    ev_temp = np.full(len(ev_hour), 0.0)
    # event day is hot: design-ish conditions
    ev_temp[:] = DESIGN_TEMP + rng.normal(0, 1.0)
    ev_weekend = np.zeros(len(ev_hour), dtype=bool)

    counterfactual = simulate_load(hh, ev_temp, ev_hour, ev_weekend, rng)
    # what the household can actually shed: its cooling load, times willingness,
    # plus a small behavioural (non-cooling) shed.
    ac_load = (hh["ac_slope"][:, None] * np.clip(ev_temp[None, :] - 65.0, 0, None)
               * ac_duty(ev_hour[None, :]))
    shed = (hh["willingness"][:, None] * ac_load
            + 0.10 * hh["willingness"][:, None] * hh["evening"][:, None])
    actual = np.clip(counterfactual - shed, 0.02, None)

    cbl = Y @ R[FEATURES.index("cbl_peak")]        # the 10-in-10 baseline, kW
    return cbl - actual.mean(axis=1), counterfactual.mean(axis=1)


# ---- ridge-regularised logistic regression (IRLS), pure numpy ----------------
def fit_logistic(F, y, lam=1.0, iters=60):
    mu, sd = F.mean(axis=0), F.std(axis=0)
    sd[sd < 1e-12] = 1.0
    A = np.column_stack([(F - mu) / sd, np.ones(len(F))])
    beta = np.zeros(A.shape[1])
    reg = np.ones(A.shape[1]); reg[-1] = 0.0
    for _ in range(iters):
        p = sigmoid(A @ beta)
        W = np.clip(p * (1 - p), 1e-6, None)
        grad = A.T @ (p - y) + lam * reg * beta
        H = (A * W[:, None]).T @ A + lam * np.diag(reg)
        beta -= np.linalg.solve(H, grad)
    coef, b = beta[:-1], beta[-1]
    return coef / sd, float(b - np.sum(coef * mu / sd))


def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-np.clip(z, -60, 60)))


def roc_auc(y, s):
    order = np.argsort(s, kind="mergesort")
    ranks = np.empty(len(s)); ranks[order] = np.arange(1, len(s) + 1)
    _, inv, cnt = np.unique(s, return_inverse=True, return_counts=True)
    sums = np.zeros(len(cnt)); np.add.at(sums, inv, ranks)
    ranks = (sums / cnt)[inv]
    npos = int(y.sum()); nneg = len(y) - npos
    if npos == 0 or nneg == 0: return float("nan")
    return (ranks[y == 1].sum() - npos * (npos + 1) / 2) / (npos * nneg)


def prf(y, pred):
    tp = int(((pred == 1) & (y == 1)).sum()); fp = int(((pred == 1) & (y == 0)).sum())
    fn = int(((pred == 0) & (y == 1)).sum())
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    return prec, rec, (2 * prec * rec / (prec + rec) if prec + rec else 0.0)


# ---- generate -----------------------------------------------------------------
hh_tr = make_households(N_TRAIN, rng)
hh_te = make_households(N_TEST, rng)
Ytr = simulate_load(hh_tr, TEMP, hour_of, is_weekend, rng)
Yte = simulate_load(hh_te, TEMP, hour_of, is_weekend, rng)

red_tr, _ = measured_reduction(hh_tr, Ytr, rng)
red_te, _ = measured_reduction(hh_te, Yte, rng)

THRESH = float(np.quantile(red_tr, 1.0 - TARGET_BASE_RATE))
ytr = (red_tr >= THRESH).astype(int)
yte = (red_te >= THRESH).astype(int)

Ftr, Fte = Ytr @ R.T, Yte @ R.T
frank = np.linalg.matrix_rank(Ftr)
assert frank == len(FEATURES), f"derived features are rank-deficient: {frank} of {len(FEATURES)}"

w, bias = fit_logistic(Ftr, ytr, lam=1.0)
logit_tr, logit_te = Ftr @ w + bias, Fte @ w + bias
phat_te = sigmoid(logit_te)
pred_te = (phat_te > 0.5).astype(int)

# in-circuit sigmoid domain: symmetric, matched to the MEASURED logit range plus
# a margin. Matching the domain to the operand range (rather than padding it out)
# is what keeps the degree-13 Chebyshev fit accurate -- a wider interval smears
# the same degree across a steeper function.
B = float(np.ceil(max(np.abs(logit_tr).max(), np.abs(logit_te).max()) + 1.0))
SIG_LO, SIG_HI, DEGREE = -B, B, 13

acc = float((pred_te == yte).mean())
auc = float(roc_auc(yte, phat_te))
prec, rec, f1 = prf(yte, pred_te)

# ---- achievable ceiling ------------------------------------------------------
# `willingness` is behavioural and never visible in metered load, so no model
# fitted to the baseline period can predict event response perfectly. The ceiling
# is what a model with PERFECT knowledge of every physical household parameter
# (but still blind to willingness) achieves. Reporting the model's score without
# this number makes an AUC uninterpretable.
PHYS = ("base", "morning", "evening", "midday", "weekend_lift", "ac_slope")
Otr = np.column_stack([hh_tr[k] for k in PHYS])
Ote = np.column_stack([hh_te[k] for k in PHYS])
w_o, b_o = fit_logistic(Otr, ytr, lam=1.0)
p_oracle = sigmoid(Ote @ w_o + b_o)
ceil_acc = float(((p_oracle > 0.5).astype(int) == yte).mean())
ceil_auc = float(roc_auc(yte, p_oracle))

# ---- write the PUBLIC derivation ---------------------------------------------
os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
with open(os.path.join(HERE, "derivation.txt"), "w") as f:
    f.write("# PUBLIC derivation (CalTRACK/TOWT). Built from calendar + weather only,\n")
    f.write("# so it contains nothing about any household. feature_j = row_j . y\n")
    f.write(f"series_len {HOURS}\n")
    f.write(f"rotsum_window {1 << int(np.ceil(np.log2(HOURS)))}\n")
    for name, r in zip(FEATURES, R):
        f.write(f"row {name} " + " ".join(f"{v:.10e}" for v in r) + "\n")

# ---- write the CONFIDENTIAL model --------------------------------------------
with open(os.path.join(HERE, "model.txt"), "w") as f:
    f.write("# CONFIDENTIAL: the utility's scoring layer. Held by the server, never\n")
    f.write("# disclosed to the household. Committed here only so the demo runs.\n")
    f.write("features " + " ".join(FEATURES) + "\n")
    f.write("w " + " ".join(f"{v:.10e}" for v in w) + "\n")
    f.write(f"bias {bias:.10e}\n")
    f.write(f"sigmoid_lo {SIG_LO:.8f}\n")
    f.write(f"sigmoid_hi {SIG_HI:.8f}\n")
    f.write(f"sigmoid_degree {DEGREE}\n")


def write_inputs(path, Y):
    with open(path, "w") as f:
        f.write(f"# each row: {HOURS} hourly kWh values ({DAYS} days x 24 h), day 0 = Monday\n")
        for row in Y:
            f.write(",".join(f"{v:.5f}" for v in row) + "\n")


write_inputs(os.path.join(ROOT, "data", "train_inputs.csv"), Ytr[:100])
write_inputs(os.path.join(ROOT, "data", "test_inputs.csv"), Yte)

with open(os.path.join(ROOT, "data", "test_labels.csv"), "w") as f:
    f.write("# MEASURED answer key: reduction_kw is the 10-in-10 CBL minus the actual\n")
    f.write("# event-window load, averaged over the event hours. y_true = reduction >= threshold.\n")
    f.write("idx,y_true,reduction_kw\n")
    for i, (yt, rd) in enumerate(zip(yte, red_te)):
        f.write(f"{i},{int(yt)},{rd:.8f}\n")

# ---- report -------------------------------------------------------------------
op_max = float(np.abs((w[:, None] * R)[:, None, :] * Yte[None, :, :]).max())
print("=== CalTRACK/TOWT derivation + confidential model ===")
print(f"seed                : {SEED}")
print(f"baseline period     : {DAYS} days x 24 h = {HOURS} hourly values / household")
print(f"TOWT design matrix  : {X.shape[0]} x {P} (48 time-of-week + 3 cooling), full rank")
print(f"train / test        : {N_TRAIN} / {N_TEST} households")
print(f"event window        : hours {EVENT_HOURS[0]}-{EVENT_HOURS[-1]} (5-9pm) at {DESIGN_TEMP:.0f}F")
print(f"eligibility rule    : measured reduction >= {THRESH:.4f} kW (10-in-10 CBL minus actual)")
print(f"test base rate      : {100*yte.mean():.1f}% eligible (measured labels)")
print(f"derived features    : {', '.join(FEATURES)}")
print(f"feature cond number : {np.linalg.cond(Ftr):.3e}  (rank {frank}/{len(FEATURES)})")
print(f"logit train range   : [{logit_tr.min():.3f}, {logit_tr.max():.3f}]  std={logit_tr.std():.3f}")
print(f"sigmoid domain      : [{SIG_LO:.2f}, {SIG_HI:.2f}]  degree={DEGREE}")
print(f"max |w*r*y| per slot: {op_max:.3e}  (CKKS operand magnitude sanity check)")
print("---- confidential model quality vs the MEASURED labels ----")
print(f"ROC-AUC             : {auc:.3f}   (ceiling {ceil_auc:.3f})")
print(f"  ceiling = a model with perfect knowledge of every physical household")
print(f"  parameter but still blind to behavioural willingness.")
# Quality is quoted at a recruitment depth, the way a utility consumes a targeting
# score, rather than at a probability cut. See the README for why top 20%.
rank = np.argsort(-phat_te)
base_te = float(yte.mean())
print(f"--- operating point: top {TOP_FRACTION*100:.0f}% by score ---")
k = max(1, int(round(len(yte) * TOP_FRACTION)))
ncap = int(yte[rank[:k]].sum())
print(f"households recruited: {k} of {len(yte)}")
print(f"precision (hit rate): {ncap/k:.3f}   vs {base_te:.3f} if recruited at random")
print(f"lift over random    : {(ncap/k)/base_te:.2f}x")
print(f"eligibles captured  : {100*ncap/int(yte.sum()):.1f}%  ({ncap} of {int(yte.sum())})")
print(f"wrote               : model/derivation.txt (public), model/model.txt (confidential)")
print(f"                      data/test_inputs.csv, data/train_inputs.csv, data/test_labels.csv")
