# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
#
# Stage 3 reference generator: a seeded synthetic demand-response eligibility
# problem. Produces
#   - model/model.txt        the fixed logistic-regression model (weights + bias +
#                            in-circuit sigmoid domain/degree). Known to the utility.
#   - data/train_inputs.csv  representative households used to calibrate the
#                            sigmoid domain (Stage 3 activation-range check).
#   - data/test_inputs.csv   held-out households scored end to end.
#
# The model scores a household's 24-value hourly kWh profile PLUS two aggregates
# derived from that profile inside the model:
#   total_daily = sum(x[0:24])
#   evening_peak = sum(x[17:22])   (hours 17,18,19,20,21)
# logit = w_hourly . x + w_total*total_daily + w_peak*evening_peak + bias
# prob  = sigmoid(logit);  eligible = prob > 0.5.
import numpy as np, json, os

SEED = 20260730
rng = np.random.default_rng(SEED)
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PEAK = list(range(17, 22))  # evening-peak hours 17..21 inclusive

def make_profiles(n):
    """Synthetic 24-hour household kWh profiles (kWh per hour)."""
    prof = np.zeros((n, 24))
    hours = np.arange(24)
    for i in range(n):
        base = rng.uniform(0.15, 0.5)                      # always-on load
        # morning bump around 7-9
        morn = rng.uniform(0.3, 1.2) * np.exp(-0.5 * ((hours - 8) / 1.4) ** 2)
        # evening peak around 18-20, strength varies a lot across households
        eve_strength = rng.uniform(0.2, 3.5)
        eve = eve_strength * np.exp(-0.5 * ((hours - 19) / 1.7) ** 2)
        # midday (some households have daytime occupancy / solar-shifted use)
        mid = rng.uniform(0.0, 0.8) * np.exp(-0.5 * ((hours - 13) / 2.5) ** 2)
        noise = rng.normal(0, 0.05, 24)
        p = base + morn + eve + mid + noise
        prof[i] = np.clip(p, 0.02, None)
    return prof

def aggregates(x):
    total = x[:, :24].sum(axis=1)
    peak = x[:, PEAK].sum(axis=1)
    return total, peak

def features(x):
    total, peak = aggregates(x)
    return np.column_stack([x, total, peak])  # (n, 26)

# ---- design the fixed model -------------------------------------------------
# Good demand-response candidates have their consumption concentrated in the
# evening peak (they can shift a lot of load). Weight the evening-peak hours and
# the evening-peak aggregate positively; penalise flat / midday-heavy use.
w_hourly = np.zeros(24)
for h in range(24):
    if h in PEAK:
        w_hourly[h] = 0.35            # concentrated evening use is good
    elif 10 <= h <= 15:
        w_hourly[h] = -0.20           # midday-heavy use is a poorer candidate
    else:
        w_hourly[h] = 0.02
w_total = -0.15                        # very high total usage slightly penalised
w_peak = 0.55                          # evening-peak aggregate is the strongest signal
w = np.concatenate([w_hourly, [w_total, w_peak]])

# Calibrate a global scale + bias on the training set so logits sit in a compact
# band (Stage 3: keep pre-activation within roughly +-8 so a low-degree Chebyshev
# sigmoid is both safe and accurate), and eligibility is a meaningful ~40-55%.
Xtr = make_profiles(2000)
Ftr = features(Xtr)
raw = Ftr @ w
scale = 3.0 / raw.std()               # target logit std ~ 3
bias = -scale * np.median(raw)        # center the decision boundary near the median
w_s = w * scale
logit_tr = Ftr @ w_s + bias

lo = float(np.floor(logit_tr.min() - 1.0))
hi = float(np.ceil(logit_tr.max() + 1.0))
# symmetric domain (sigmoid is centered at 0) with margin
B = float(max(abs(lo), abs(hi)))
SIG_LO, SIG_HI = -B, B
DEGREE = 13

elig_rate = float((1.0 / (1.0 + np.exp(-logit_tr)) > 0.5).mean())

# ---- write model.txt (whitespace-separated, trivial to parse in C++) --------
os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
with open(os.path.join(HERE, "model.txt"), "w") as f:
    f.write("# demand-response eligibility model (logistic regression + in-circuit sigmoid)\n")
    f.write("# format: keyword values\n")
    f.write("w_hourly " + " ".join(f"{v:.8f}" for v in w_s[:24]) + "\n")
    f.write(f"w_total {w_s[24]:.8f}\n")
    f.write(f"w_peak {w_s[25]:.8f}\n")
    f.write(f"bias {bias:.8f}\n")
    f.write(f"sigmoid_lo {SIG_LO:.8f}\n")
    f.write(f"sigmoid_hi {SIG_HI:.8f}\n")
    f.write(f"sigmoid_degree {DEGREE}\n")
    f.write("peak_hours " + " ".join(str(h) for h in PEAK) + "\n")

# ---- write data -------------------------------------------------------------
def write_inputs(path, X):
    with open(path, "w") as f:
        f.write("# each row: 24 hourly kWh values (hour 0..23)\n")
        for row in X:
            f.write(",".join(f"{v:.6f}" for v in row) + "\n")

write_inputs(os.path.join(ROOT, "data", "train_inputs.csv"), Xtr[:200])
Xte = make_profiles(200)
write_inputs(os.path.join(ROOT, "data", "test_inputs.csv"), Xte)

print("=== model + data generated ===")
print(f"seed                : {SEED}")
print(f"logit train range   : [{logit_tr.min():.3f}, {logit_tr.max():.3f}]  std={logit_tr.std():.3f}")
print(f"sigmoid domain      : [{SIG_LO:.2f}, {SIG_HI:.2f}]  degree={DEGREE}")
print(f"eligibility rate    : {elig_rate*100:.1f}%")
print(f"model.txt           : {os.path.join(HERE,'model.txt')}")
print(f"test set            : 200 households -> data/test_inputs.csv")
