# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
#
# Stage 3 reference generator: a seeded synthetic demand-response eligibility
# problem with an INDEPENDENT ground truth. Produces
#   - model/model.txt        the FITTED logistic-regression model (weights + bias +
#                            in-circuit sigmoid domain/degree). Known to the utility.
#   - data/train_inputs.csv  representative households (calibration sample).
#   - data/test_inputs.csv   held-out households scored end to end.
#   - data/test_labels.csv   the held-out households' TRUE eligibility labels
#                            (idx, y_true, p_true) — the answer key for quality metrics.
#
# HOW THE GROUND TRUTH IS DEFINED (this is the point of the design):
#   1. Draw a household's 24-hour kWh profile x (seeded).
#   2. A fixed *latent* process decides who is genuinely a good demand-response
#      candidate. It keys off physically meaningful, NON-LINEAR summaries of the
#      profile — the evening-peak SHARE (peak / total), the absolute shiftable
#      evening load, the midday share, and overall size — producing a true
#      probability p_true = sigmoid(true_score - offset). The offset is tuned for a
#      documented base rate (~1/3 of households genuinely eligible), NOT 50/50.
#   3. The label y ~ Bernoulli(p_true). Labels carry real noise: even the latent
#      process is not deterministic, so NO model can score 100%.
#   4. We then FIT the utility's logistic model (its fixed shape: 24 hourly weights
#      + a total-use weight + an evening-peak weight + bias) to predict y on a
#      TRAIN split. Because the truth depends on ratios (nonlinear in x) and the
#      labels are noisy, the fitted linear model is a genuine, imperfect predictor
#      of an independent label — not the label's source.
#
# The model still scores a household's 24-value hourly kWh profile PLUS two
# aggregates the circuit derives from it:
#   total_daily  = sum(x[0:24])
#   evening_peak = sum(x[17:22])   (hours 17,18,19,20,21)
# logit = w_hourly . x + w_total*total_daily + w_peak*evening_peak + bias
# prob  = sigmoid(logit);  eligible = prob > 0.5.
import numpy as np, os

SEED = 20260730
rng = np.random.default_rng(SEED)
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PEAK = list(range(17, 22))   # evening-peak hours 17..21 inclusive
MIDDAY = list(range(10, 16)) # midday hours 10..15 inclusive

def make_profiles(n):
    """Synthetic 24-hour household kWh profiles (kWh per hour)."""
    prof = np.zeros((n, 24))
    hours = np.arange(24)
    for i in range(n):
        base = rng.uniform(0.15, 0.5)                      # always-on load
        morn = rng.uniform(0.3, 1.2) * np.exp(-0.5 * ((hours - 8) / 1.4) ** 2)
        eve_strength = rng.uniform(0.2, 3.5)               # evening peak strength varies a lot
        eve = eve_strength * np.exp(-0.5 * ((hours - 19) / 1.7) ** 2)
        mid = rng.uniform(0.0, 0.8) * np.exp(-0.5 * ((hours - 13) / 2.5) ** 2)
        noise = rng.normal(0, 0.05, 24)
        p = base + morn + eve + mid + noise
        prof[i] = np.clip(p, 0.02, None)
    return prof

def aggregates(x):
    total = x[:, :24].sum(axis=1)
    peak = x[:, PEAK].sum(axis=1)
    return total, peak

def features(x):
    total, peak = aggregates(x)
    return np.column_stack([x, total, peak])  # (n, 26): the model's inputs

def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-np.clip(z, -60, 60)))

# ---- the independent latent "truth" -----------------------------------------
def latent_score(x):
    """A fixed latent process scoring genuine DR suitability from physical summaries
    of the profile. Mixes signal a linear-in-x model CAN capture (absolute evening
    load) with signal it can only approximate (evening-peak SHARE, a nonlinear
    ratio), so the fitted logistic is a strong-but-imperfect predictor."""
    total = x[:, :24].sum(axis=1)
    peak = x[:, PEAK].sum(axis=1)
    midday = x[:, MIDDAY].sum(axis=1)
    peak_share = peak / total                 # fraction of the day used in the evening peak
    midday_share = midday / total             # daytime-heavy use is a poorer candidate
    shiftable = peak                          # absolute kWh available to shift in the evening
    return (8.0 * peak_share
            + 1.6 * np.log1p(shiftable)
            - 4.0 * midday_share
            - 0.12 * total
            + 2.0 * peak_share ** 2)          # extra reward for very peaky users (nonlinear)

def true_prob(x, offset):
    return sigmoid(latent_score(x) - offset)

def calibrate_offset(x, target_rate):
    """Pick the latent offset so E[p_true] hits the target base rate (bisection)."""
    score = latent_score(x)
    lo, hi = score.min() - 5.0, score.max() + 5.0
    for _ in range(60):
        mid = 0.5 * (lo + hi)
        if sigmoid(score - mid).mean() > target_rate: lo = mid
        else: hi = mid
    return 0.5 * (lo + hi)

# ---- ridge-regularised logistic regression (IRLS), pure numpy ----------------
def fit_logistic(F, y, lam=2.0, iters=60):
    """Fit on standardised features for conditioning, then fold the standardisation
    back so the returned (w, b) act on the RAW features the circuit uses."""
    mu = F.mean(axis=0); sd = F.std(axis=0); sd[sd < 1e-8] = 1.0
    Xs = (F - mu) / sd
    n, d = Xs.shape
    A = np.column_stack([Xs, np.ones(n)])     # last column = intercept
    beta = np.zeros(d + 1)
    reg = np.ones(d + 1); reg[-1] = 0.0        # don't penalise the intercept
    for _ in range(iters):
        eta = A @ beta
        p = sigmoid(eta)
        W = np.clip(p * (1 - p), 1e-6, None)
        grad = A.T @ (p - y) + lam * reg * beta
        H = (A * W[:, None]).T @ A + lam * np.diag(reg)
        beta -= np.linalg.solve(H, grad)
    coef_s, b_s = beta[:-1], beta[-1]
    w_raw = coef_s / sd                        # fold standardisation into raw weights
    b_raw = b_s - np.sum(coef_s * mu / sd)
    return w_raw, float(b_raw)

# ---- metrics (pure numpy) ----------------------------------------------------
def roc_auc(y, s):
    order = np.argsort(s, kind="mergesort")
    ranks = np.empty(len(s)); ranks[order] = np.arange(1, len(s) + 1)
    # average ranks for ties
    _, inv, cnt = np.unique(s, return_inverse=True, return_counts=True)
    sums = np.zeros(len(cnt)); np.add.at(sums, inv, ranks)
    ranks = (sums / cnt)[inv]
    n_pos = int(y.sum()); n_neg = len(y) - n_pos
    if n_pos == 0 or n_neg == 0: return float("nan")
    return (ranks[y == 1].sum() - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg)

def prf(y, pred):
    tp = int(((pred == 1) & (y == 1)).sum()); fp = int(((pred == 1) & (y == 0)).sum())
    fn = int(((pred == 0) & (y == 1)).sum())
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * prec * rec / (prec + rec) if prec + rec else 0.0
    return prec, rec, f1

# ---- generate data, fit, calibrate the in-circuit sigmoid --------------------
BASE_RATE = 1.0 / 3.0                          # documented target: ~1/3 genuinely eligible
Xtr = make_profiles(6000)
Xte = make_profiles(400)
offset = calibrate_offset(Xtr, BASE_RATE)

ptr = true_prob(Xtr, offset); ytr = (rng.uniform(size=len(Xtr)) < ptr).astype(int)
pte = true_prob(Xte, offset); yte = (rng.uniform(size=len(Xte)) < pte).astype(int)

Ftr = features(Xtr); Fte = features(Xte)
w, bias = fit_logistic(Ftr, ytr, lam=2.0)

logit_tr = Ftr @ w + bias
logit_te = Fte @ w + bias
phat_te = sigmoid(logit_te)
pred_te = (phat_te > 0.5).astype(int)

# in-circuit sigmoid domain: symmetric, covering the fitted train logits + margin.
# The width is floored at 8: OpenFHE's EvalLogistic Chebyshev fit is calibrated on a
# domain wide enough for the logistic to saturate at the endpoints, and a too-narrow
# interval degrades its accuracy relative to the twin. 8 covers the fitted logits
# (|logit| well under 6) with generous margin while keeping the in-circuit sigmoid
# faithful to the twin.
B = float(max(8.0, np.ceil(np.abs(logit_tr).max() + 1.0)))
SIG_LO, SIG_HI = -B, B
DEGREE = 13

# quality of the FITTED model against the INDEPENDENT test labels.
acc = float((pred_te == yte).mean())
auc = float(roc_auc(yte, phat_te))
prec, rec, f1 = prf(yte, pred_te)
base_rate_te = float(yte.mean())

# ---- write model.txt (whitespace-separated, trivial to parse in C++) --------
os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
with open(os.path.join(HERE, "model.txt"), "w") as f:
    f.write("# demand-response eligibility model (logistic regression + in-circuit sigmoid)\n")
    f.write("# FITTED to independent Bernoulli labels; format: keyword values\n")
    f.write("w_hourly " + " ".join(f"{v:.8f}" for v in w[:24]) + "\n")
    f.write(f"w_total {w[24]:.8f}\n")
    f.write(f"w_peak {w[25]:.8f}\n")
    f.write(f"bias {bias:.8f}\n")
    f.write(f"sigmoid_lo {SIG_LO:.8f}\n")
    f.write(f"sigmoid_hi {SIG_HI:.8f}\n")
    f.write(f"sigmoid_degree {DEGREE}\n")
    f.write("peak_hours " + " ".join(str(h) for h in PEAK) + "\n")

# ---- write data -------------------------------------------------------------
def write_inputs(path, X):
    with open(path, "w") as f:
        f.write("# each row: 24 hourly kWh values (hour 0..23)\n")
        for row in X:
            f.write(",".join(f"{v:.6f}" for v in row) + "\n")

write_inputs(os.path.join(ROOT, "data", "train_inputs.csv"), Xtr[:200])
write_inputs(os.path.join(ROOT, "data", "test_inputs.csv"), Xte)

with open(os.path.join(ROOT, "data", "test_labels.csv"), "w") as f:
    f.write("# independent ground truth for the held-out households.\n")
    f.write("# y_true ~ Bernoulli(p_true); this is NOT the model's output.\n")
    f.write("idx,y_true,p_true\n")
    for i, (yt, pt) in enumerate(zip(yte, pte)):
        f.write(f"{i},{int(yt)},{pt:.8f}\n")

print("=== model FITTED + labeled data generated ===")
print(f"seed                : {SEED}")
print(f"train / test        : {len(Xtr)} / {len(Xte)} households")
print(f"target base rate    : {BASE_RATE*100:.1f}%   (latent offset={offset:.3f})")
print(f"test base rate      : {base_rate_te*100:.1f}% positive (true labels)")
print(f"logit train range   : [{logit_tr.min():.3f}, {logit_tr.max():.3f}]  std={logit_tr.std():.3f}")
print(f"sigmoid domain      : [{SIG_LO:.2f}, {SIG_HI:.2f}]  degree={DEGREE}")
print("---- fitted-model quality vs INDEPENDENT test labels ----")
print(f"accuracy            : {acc:.3f}")
print(f"ROC-AUC             : {auc:.3f}")
print(f"precision/recall/F1 : {prec:.3f} / {rec:.3f} / {f1:.3f}")
print(f"model.txt           : {os.path.join(HERE,'model.txt')}")
print(f"test set + labels   : data/test_inputs.csv, data/test_labels.csv")
