# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
#
# Stages 3/5/6/7: the reference and the faithful twin, plus validation.
#
#   reference(y) : feature_j = row_j . y   (the PUBLIC CalTRACK/TOWT derivation)
#                  logit = w . features + bias      (the CONFIDENTIAL model)
#                  prob  = true sigmoid(logit)
#   twin(y)      : SAME derivation, SAME logit; prob = Chebyshev interpolant of
#                  the logistic over [sigmoid_lo, sigmoid_hi] at sigmoid_degree --
#                  the EXACT function the encrypted circuit evaluates via
#                  OpenFHE EvalLogistic.
#
# Reference and twin share identical linear algebra and differ ONLY in the
# sigmoid, so twin-vs-reference isolates the polynomial-approximation cost.
#
# The six derived quantities are computed here exactly as the encrypted circuit
# computes them: multiply the 672-slot series by each row vector and sum the
# slots (rotate-and-sum in the circuit, a dot product here).
import numpy as np, os
from numpy.polynomial import chebyshev as C

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def load_derivation(path=None):
    path = path or os.path.join(HERE, "derivation.txt")
    names, rows, meta = [], [], {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if parts[0] == "row":
                names.append(parts[1])
                rows.append([float(v) for v in parts[2:]])
            else:
                meta[parts[0]] = int(parts[1])
    return names, np.array(rows), meta


def load_model(path=None):
    path = path or os.path.join(HERE, "model.txt")
    m = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            k = parts[0]
            if k == "features":
                m[k] = parts[1:]
            elif k == "w":
                m[k] = np.array([float(v) for v in parts[1:]])
            elif k == "sigmoid_degree":
                m[k] = int(parts[1])
            else:
                m[k] = float(parts[1])
    return m


def load_inputs(path):
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            rows.append([float(v) for v in line.split(",")])
    return np.array(rows)


def load_labels(path):
    y = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            try:
                y.append(int(line.split(",")[1]))
            except ValueError:      # skip the CSV header row
                continue
    return np.array(y)


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def logit(Y, names, R, m):
    """features = Y @ R.T in the derivation's row order, then the confidential
    linear layer. Row order is matched to the model's feature order by NAME."""
    idx = [names.index(f) for f in m["features"]]
    F = Y @ R[idx].T
    return F @ m["w"] + m["bias"], F


def cheb_sigmoid_factory(lo, hi, deg):
    coeffs = C.chebinterpolate(lambda t: sigmoid(0.5 * (hi - lo) * t + 0.5 * (hi + lo)), deg)
    def f(x):
        t = 2.0 * (np.asarray(x) - lo) / (hi - lo) - 1.0
        return C.chebval(t, coeffs)
    return f


def roc_auc(y, s):
    order = np.argsort(s, kind="mergesort")
    ranks = np.empty(len(s)); ranks[order] = np.arange(1, len(s) + 1)
    _, inv, cnt = np.unique(s, return_inverse=True, return_counts=True)
    sums = np.zeros(len(cnt)); np.add.at(sums, inv, ranks)
    ranks = (sums / cnt)[inv]
    npos = int(y.sum()); nneg = len(y) - npos
    if npos == 0 or nneg == 0: return float("nan")
    return (ranks[y == 1].sum() - npos * (npos + 1) / 2) / (npos * nneg)


def prf(y, pred):
    tp = int(((pred == 1) & (y == 1)).sum()); fp = int(((pred == 1) & (y == 0)).sum())
    fn = int(((pred == 0) & (y == 1)).sum())
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    return prec, rec, (2 * prec * rec / (prec + rec) if prec + rec else 0.0)


# The deployed protocol scores one household, which thresholds its own probability
# at 0.5, so that is the operating point reported first. at_depth() supports the
# supplementary view of the same score under a ranked deployment.
def at_depth(y, s, frac):
    """(recruited, precision, capture, lift, n_captured) at a recruitment depth."""
    order = np.argsort(-s)
    n, npos = len(y), int(y.sum())
    k = max(1, int(round(n * frac)))
    cap = int(y[order[:k]].sum())
    prec, base = cap / k, npos / n
    return k, prec, (cap / npos if npos else float("nan")), prec / base, cap


def main():
    names, R, meta = load_derivation()
    m = load_model()
    Y = load_inputs(os.path.join(ROOT, "data", "test_inputs.csv"))
    yte = load_labels(os.path.join(ROOT, "data", "test_labels.csv"))
    lo, hi, deg = m["sigmoid_lo"], m["sigmoid_hi"], m["sigmoid_degree"]

    if Y.shape[1] != meta["series_len"]:
        raise SystemExit(f"input width {Y.shape[1]} != derivation series_len {meta['series_len']}")

    z, F = logit(Y, names, R, m)
    p_ref = sigmoid(z)
    twin_sig = cheb_sigmoid_factory(lo, hi, deg)
    p_twin = twin_sig(z)
    lab_ref = (p_ref > 0.5).astype(int)
    lab_twin = (p_twin > 0.5).astype(int)

    print("=== Stage 5: boundary representation (derivation + model) ===")
    print(f"baseline series     : {meta['series_len']} hourly values "
          f"(rotate-and-sum window {meta['rotsum_window']})")
    print(f"derived quantities  : {', '.join(m['features'])}")

    print("\n=== Stage 3: task metric, confidential model vs the MEASURED labels ===")
    base = float(yte.mean())
    print(f"records             : {len(Y)}")
    print(f"base rate           : {100*base:.1f}% eligible (measured reduction >= threshold)")
    print(f"ROC-AUC             : {roc_auc(yte, p_ref):.3f}   (ranking quality, threshold-free)")
    sel = p_ref > 0.5
    k = int(sel.sum()); tp = int(yte[sel].sum()); npos = int(yte.sum())
    print("--- the answer a household receives: its own score, thresholded at 0.5 ---")
    print(f"told eligible       : {k} of {len(Y)} households ({100*k/len(Y):.1f}%)")
    print(f"precision           : {tp/k:.3f}   told eligible and truly eligible")
    print(f"                      {base:.3f} for a household picked at random ({(tp/k)/base:.2f}x)")
    print(f"recall              : {tp/npos:.3f}   of truly eligible households are told so")
    print("--- the same score at fixed selection depths (for a ranked deployment) ---")
    print(f"{'depth':>6} {'recruited':>10} {'precision':>10} {'capture':>9} {'lift':>6}")
    for d in (1, 2, 3, 4, 5):
        kk, pp, cc, ll, _ = at_depth(yte, p_ref, d / 10)
        print(f"{d*10:>5}% {kk:>10} {pp:>10.3f} {100*cc:>8.1f}% {ll:>6.2f}")

    print("\n=== Stage 3: activation-range feasibility check ===")
    print(f"logit (sigmoid input) test range: [{z.min():.3f}, {z.max():.3f}]  "
          f"p0.1-p99.9=[{np.percentile(z,0.1):.3f}, {np.percentile(z,99.9):.3f}]")
    covered = bool(z.min() >= lo and z.max() <= hi)
    print(f"sigmoid domain [{lo:.2f}, {hi:.2f}] covers range: {covered}  -> grade: "
          f"{'EASY (bulk in band, no tail)' if covered else 'needs filter/model change'}")

    prob_err = np.abs(p_twin - p_ref)
    flips = int((lab_twin != lab_ref).sum())
    print("\n=== Stage 7: twin vs reference (polynomial-approximation cost) ===")
    print(f"records             : {len(Y)}")
    print(f"max |prob twin-ref| : {prob_err.max():.3e}")
    print(f"mean|prob twin-ref| : {prob_err.mean():.3e}")
    print(f"decision agreement  : {(lab_twin==lab_ref).mean()*100:.2f}%  (flips={flips})")

    margin = np.abs(p_twin - 0.5)
    print("\n=== Stage 7: application-level noise tolerance ===")
    print(f"min decision margin |prob-0.5| over test set (twin): {margin.min():.3e}")
    print(f"  -> encryption output error below this => 0 decision flips.")
    print(f"median margin: {np.median(margin):.3e}")
    if prob_err.max() >= margin.min():
        n_at_risk = int((margin < prob_err.max()).sum())
        print(f"NOTE: the polynomial error ({prob_err.max():.2e}) exceeds the minimum "
              f"decision margin ({margin.min():.2e});")
        print(f"      {n_at_risk} of {len(Y)} households sit closer to 0.5 than that error.")
    else:
        print(f"the polynomial error ({prob_err.max():.2e}) is BELOW the minimum decision "
              f"margin, so no household\n      can be flipped by the approximation.")

    with open(os.path.join(ROOT, "data", "reference_outputs.csv"), "w") as f:
        f.write("# prob_reference,decision_reference,y_true\n")
        for p, l, yt in zip(p_ref, lab_ref, yte):
            f.write(f"{p:.10f},{l},{int(yt)}\n")
    with open(os.path.join(ROOT, "data", "twin_outputs.csv"), "w") as f:
        f.write("# prob_twin,decision_twin,y_true\n")
        for p, l, yt in zip(p_twin, lab_twin, yte):
            f.write(f"{p:.10f},{l},{int(yt)}\n")
    with open(os.path.join(ROOT, "data", "noise_tolerance.txt"), "w") as f:
        f.write(f"{margin.min():.10e}\n")
    print("\nwrote data/reference_outputs.csv, data/twin_outputs.csv, data/noise_tolerance.txt")


if __name__ == "__main__":
    main()
