# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
#
# Stages 3/5/6/7: the reference and the faithful twin, plus validation.
#
#   reference(x): logit = w.[x, total, peak] + bias ; prob = true sigmoid(logit)
#   twin(x)     : SAME logit ; prob = Chebyshev-interpolant sigmoid over
#                 [sigmoid_lo, sigmoid_hi] at sigmoid_degree -- the EXACT function
#                 the encrypted circuit evaluates via OpenFHE EvalLogistic.
#
# The aggregates (total_daily, evening_peak) are computed here the same way the
# encrypted circuit computes them: a sum over the 24 slots, and a masked sum over
# the evening-peak slots. Both reference and twin use identical linear algebra;
# they differ ONLY in the sigmoid (true vs polynomial), so twin-vs-reference
# isolates the polynomial-approximation cost.
import numpy as np, os
from numpy.polynomial import chebyshev as C

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

def load_model():
    m = {}
    with open(os.path.join(HERE, "model.txt")) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            k = parts[0]
            if k == "w_hourly":
                m[k] = np.array([float(v) for v in parts[1:]])
            elif k == "peak_hours":
                m[k] = [int(v) for v in parts[1:]]
            elif k == "sigmoid_degree":
                m[k] = int(parts[1])
            else:
                m[k] = float(parts[1])
    return m

def load_inputs(path):
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            rows.append([float(v) for v in line.split(",")])
    return np.array(rows)

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def logit(X, m):
    total = X[:, :24].sum(axis=1)
    peak = X[:, m["peak_hours"]].sum(axis=1)
    return X @ m["w_hourly"] + m["w_total"] * total + m["w_peak"] * peak + m["bias"]

def cheb_sigmoid_factory(lo, hi, deg):
    # Chebyshev interpolation of the logistic on [lo,hi] -- mirrors OpenFHE
    # EvalLogistic / EvalChebyshevFunction (interpolation at Chebyshev nodes).
    coeffs = C.chebinterpolate(lambda t: sigmoid(0.5 * (hi - lo) * t + 0.5 * (hi + lo)), deg)
    def f(x):
        t = 2.0 * (np.asarray(x) - lo) / (hi - lo) - 1.0
        return C.chebval(t, coeffs)
    return f

def main():
    m = load_model()
    Xte = load_inputs(os.path.join(ROOT, "data", "test_inputs.csv"))
    lo, hi, deg = m["sigmoid_lo"], m["sigmoid_hi"], m["sigmoid_degree"]

    z = logit(Xte, m)
    p_ref = sigmoid(z)
    twin_sig = cheb_sigmoid_factory(lo, hi, deg)
    p_twin = twin_sig(z)

    lab_ref = (p_ref > 0.5).astype(int)
    lab_twin = (p_twin > 0.5).astype(int)

    # ---- Stage 3 activation-range feasibility check ----
    print("=== Stage 3: activation-range feasibility check ===")
    print(f"logit (sigmoid input) test range: [{z.min():.3f}, {z.max():.3f}]  "
          f"p0.1-p99.9=[{np.percentile(z,0.1):.3f}, {np.percentile(z,99.9):.3f}]")
    print(f"sigmoid domain [{lo:.2f}, {hi:.2f}] covers range: "
          f"{bool(z.min() >= lo and z.max() <= hi)}  -> grade: "
          f"{'EASY (bulk in band, no tail)' if (z.min()>=lo and z.max()<=hi) else 'needs filter/model change'}")

    # ---- Stage 7: twin vs reference (polynomial cost) ----
    prob_err = np.abs(p_twin - p_ref)
    flips = int((lab_twin != lab_ref).sum())
    print("\n=== Stage 7: twin vs reference (polynomial-approximation cost) ===")
    print(f"records             : {len(Xte)}")
    print(f"max |prob twin-ref| : {prob_err.max():.3e}")
    print(f"mean|prob twin-ref| : {prob_err.mean():.3e}")
    print(f"decision agreement  : {(lab_twin==lab_ref).mean()*100:.2f}%  (flips={flips})")
    print(f"eligible (reference): {lab_ref.mean()*100:.1f}%")

    # ---- application-level noise tolerance (Stage 7) ----
    # A decision flips only if encryption noise moves prob across 0.5. The
    # tightest test-set margin is the tolerance the encrypted run must clear.
    margin = np.abs(p_twin - 0.5)
    print("\n=== Stage 7: application-level noise tolerance ===")
    print(f"min decision margin |prob-0.5| over test set (twin): {margin.min():.3e}")
    print(f"  -> encryption output error below this => 0 decision flips.")
    print(f"median margin: {np.median(margin):.3e}")

    # ---- write ledgers used by run_test's FHE-vs-twin comparison ----
    with open(os.path.join(ROOT, "data", "reference_outputs.csv"), "w") as f:
        f.write("# prob_reference,label_reference\n")
        for p, l in zip(p_ref, lab_ref):
            f.write(f"{p:.10f},{l}\n")
    with open(os.path.join(ROOT, "data", "twin_outputs.csv"), "w") as f:
        f.write("# prob_twin,label_twin\n")
        for p, l in zip(p_twin, lab_twin):
            f.write(f"{p:.10f},{l}\n")
    with open(os.path.join(ROOT, "data", "noise_tolerance.txt"), "w") as f:
        f.write(f"{margin.min():.10e}\n")
    print("\nwrote data/reference_outputs.csv, data/twin_outputs.csv, data/noise_tolerance.txt")

if __name__ == "__main__":
    main()
