// Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
//
// Shared model + homomorphic circuit for the demand-response eligibility app.
//
// The circuit is factored into one run_circuit() so the --cpu path and the
// recording (--sim / Fog) path evaluate the IDENTICAL math (Stage 8 / Stage 10).
//
// The two derived aggregates are computed INSIDE the encrypted circuit, from the
// encrypted 24-hour vector:
//   total_daily  = sum_{h=0..23} x[h]                     (rotate-and-sum, window 32)
//   evening_peak = sum_{h=17..21} x[h]                    (mask hours 17..21, then sum)
// and combined with the fixed logistic-regression model:
//   logit = sum_h w_hourly[h]*x[h] + w_total*total_daily + w_peak*evening_peak + bias
//   prob  = sigmoid(logit)                                 (OpenFHE EvalLogistic)
// The model weight for each aggregate is folded into the masked plaintext used
// for its rotate-and-sum, so the aggregate's derivation stays in-circuit at no
// extra multiplicative depth.
#pragma once

#include "openfhe.h"
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

using namespace lbcrypto;

// ---------------------------------------------------------------------------
// Model (plaintext operands; known to the utility/server).
// ---------------------------------------------------------------------------
struct Model {
    std::vector<double> w_hourly;   // 24 hourly weights
    double w_total = 0.0;           // weight on total_daily aggregate
    double w_peak = 0.0;            // weight on evening_peak aggregate
    double bias = 0.0;
    double sigmoid_lo = -8.0;
    double sigmoid_hi = 8.0;
    uint32_t sigmoid_degree = 13;
    std::vector<int> peak_hours;    // e.g. {17,18,19,20,21}
};

inline Model load_model(const std::string& path) {
    Model m;
    std::ifstream f(path);
    if (!f.is_open()) throw std::runtime_error("Cannot open model file: " + path);
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ss(line);
        std::string key;
        ss >> key;
        if (key == "w_hourly") {
            double v;
            while (ss >> v) m.w_hourly.push_back(v);
        } else if (key == "w_total") ss >> m.w_total;
        else if (key == "w_peak") ss >> m.w_peak;
        else if (key == "bias") ss >> m.bias;
        else if (key == "sigmoid_lo") ss >> m.sigmoid_lo;
        else if (key == "sigmoid_hi") ss >> m.sigmoid_hi;
        else if (key == "sigmoid_degree") ss >> m.sigmoid_degree;
        else if (key == "peak_hours") { int h; while (ss >> h) m.peak_hours.push_back(h); }
    }
    if (m.w_hourly.size() != 24) throw std::runtime_error("model w_hourly must have 24 values");
    return m;
}

// ---------------------------------------------------------------------------
// Plaintext operands the circuit multiplies by. Built ONCE, before recording
// start(), so they can be tag_input()'d for the FHETCH recorder (Stage 10).
// ---------------------------------------------------------------------------
struct CircuitPlaintexts {
    Plaintext w_hourly;    // w_hourly[h] in slots 0..23
    Plaintext w_total_vec; // w_total in slots 0..23  -> EvalMult+sum = w_total*total_daily
    Plaintext w_peak_vec;  // w_peak in slots 17..21  -> EvalMult+sum = w_peak*evening_peak
    Plaintext bias_vec;    // bias in slot 0
    Plaintext mask_slot0;  // 1 in slot 0, else 0 (isolate slot 0 before activation)
};

inline CircuitPlaintexts build_plaintexts(const CryptoContext<DCRTPoly>& cc, const Model& m) {
    std::vector<double> wh(24, 0.0), wt(24, 0.0), wp(24, 0.0), bv(24, 0.0), ms(24, 0.0);
    for (int h = 0; h < 24; ++h) { wh[h] = m.w_hourly[h]; wt[h] = m.w_total; }
    for (int h : m.peak_hours) if (h >= 0 && h < 24) wp[h] = m.w_peak;
    bv[0] = m.bias;
    ms[0] = 1.0;
    CircuitPlaintexts p;
    p.w_hourly    = cc->MakeCKKSPackedPlaintext(wh);
    p.w_total_vec = cc->MakeCKKSPackedPlaintext(wt);
    p.w_peak_vec  = cc->MakeCKKSPackedPlaintext(wp);
    p.bias_vec    = cc->MakeCKKSPackedPlaintext(bv);
    p.mask_slot0  = cc->MakeCKKSPackedPlaintext(ms);
    return p;
}

// ---------------------------------------------------------------------------
// The homomorphic circuit. Result: slot 0 holds sigmoid(logit); every other
// slot holds sigmoid(0)=0.5 (isolated away by mask_slot0 so the activation is
// evaluated only on the in-domain slot-0 logit). The client reads slot 0.
// ---------------------------------------------------------------------------
inline Ciphertext<DCRTPoly> run_circuit(const CryptoContext<DCRTPoly>& cc,
                                        const Model& m,
                                        CircuitPlaintexts& p,
                                        const Ciphertext<DCRTPoly>& ct_x) {
    // rotate-and-sum over a window of 32 slots: slot 0 accumulates slots 0..31.
    // (Only slots 0..23 are populated, so slot 0 = the intended sum.)
    auto rot_sum = [&](Ciphertext<DCRTPoly> c) {
        for (int k = 1; k < 32; k <<= 1)
            c = cc->EvalAdd(c, cc->EvalRotate(c, k));
        return c;
    };

    // sum_h w_hourly[h]*x[h]
    auto hourly = rot_sum(cc->EvalMult(ct_x, p.w_hourly));
    // w_total * total_daily  (total_daily = sum of all 24 hours, computed in-circuit)
    auto total = rot_sum(cc->EvalMult(ct_x, p.w_total_vec));
    // w_peak * evening_peak  (evening_peak = sum of hours 17..21, computed in-circuit)
    auto peak = rot_sum(cc->EvalMult(ct_x, p.w_peak_vec));

    auto logit = cc->EvalAdd(cc->EvalAdd(hourly, total), peak);
    logit = cc->EvalAdd(logit, p.bias_vec);

    // isolate slot 0 so EvalLogistic only sees the in-domain logit.
    auto logit0 = cc->EvalMult(logit, p.mask_slot0);

    return cc->EvalLogistic(logit0, m.sigmoid_lo, m.sigmoid_hi, m.sigmoid_degree);
}
