# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
# Build and run happen inside the FHE-dev container (see run-in-container.sh);
# `clean` just removes the generated artifacts from this directory (all gitignored).

.PHONY: help build clean install-skill

help:
	@echo "Targets:"
	@echo "  make install-skill   fetch the fhe-application-design skill from GitHub into the"
	@echo "                       the repo's .claude/skills/ and .agents/skills/"
	@echo "  make build           configure + build the four programs (keygen/encrypt/server/decrypt); run in-container"
	@echo "  make clean           remove the build tree and all per-run artifacts"
	@echo "  run: ./run-in-container.sh \"./run_test.sh ...\"   (see ./run_test.sh --help)"

# Install the fhe-application-design skill from GitHub into both .claude/skills
# and .agents/skills/. The skill bundles the Docker build context under environment/.
SKILL_REPO ?= https://github.com/NiobiumInc/niobium-skills
SKILL_NAME ?= fhe-application-design
SKILL_ROOT ?= $(shell git rev-parse --show-toplevel 2>/dev/null || echo ..)
install-skill:
	@tmp=$$(mktemp -d) && git clone --depth 1 $(SKILL_REPO) "$$tmp/ns" && \
	for d in "$(SKILL_ROOT)/.claude/skills" "$(SKILL_ROOT)/.agents/skills"; do \
	  mkdir -p "$$d" && rm -rf "$$d/$(SKILL_NAME)" && \
	  cp -R "$$tmp/ns/skills/$(SKILL_NAME)" "$$d/$(SKILL_NAME)" && \
	  echo "installed skill to $$d/$(SKILL_NAME)"; \
	done; rm -rf "$$tmp"

# Configure + build the four programs (keygen/encrypt/server/decrypt) with CMake
# against the prebuilt OpenFHE + niobium-client in the FHE-dev image. Run in-container:
# ./run-in-container.sh "make build".
build:
	cmake -S . -B build -DCMAKE_PREFIX_PATH='/opt/niobium-client/vendor/lib/niobium-client;/opt/niobium-client/vendor/lib/openfhe'
	cmake --build build -j$$(nproc)

# Everything a build, a run_test invocation, or the two-process demo regenerates:
#   build/                       the CMake build tree
#   run_cpu/ run_sim/ run_fog/   per-run client/server homes (keys, ciphertexts)
#   run_demo/                    the two-process demo's client/server homes
#   client_home/ server_home/    homes from the README's manual two-process walkthrough
#   dr_server_workload_*/        FHETCH trace / replay directories (e.g. ..._mode_fog)
clean:
	rm -rf build run_cpu run_sim run_sim-full run_fog run_demo \
	       client_home server_home \
	       dr_server_workload_* nbcc_fhetch_replay_source_*
	@echo "clean: removed the build tree and per-run artifacts"
