# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
# Build and run happen inside the FHE-dev container (see run-in-container.sh);
# `clean` just removes the generated artifacts from this directory (all gitignored).

.PHONY: help clean

help:
	@echo "Targets:"
	@echo "  make clean   remove the build tree and all per-run artifacts"
	@echo "  build / run: ./run-in-container.sh \"...\"   (see ./run_test.sh --help)"

# Everything a build or a run_test invocation regenerates:
#   build/                       the CMake build tree
#   run_cpu/ run_sim/ run_fog/   per-run client/server homes (keys, ciphertexts)
#   client_home/ server_home/    homes from the README's manual two-process walkthrough
#   dr_server_workload_*/        FHETCH trace / replay directories (e.g. ..._mode_fog)
clean:
	rm -rf build run_cpu run_sim run_fog run_nokey \
	       client_home server_home \
	       dr_server_workload_* nbcc_fhetch_replay_source_*
	@echo "clean: removed the build tree and per-run artifacts"
