# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
# Build and run happen inside the FHE-dev container (see run-in-container.sh);
# `clean` just removes the generated artifacts from this directory (all gitignored).

.PHONY: help clean install-skill

help:
	@echo "Targets:"
	@echo "  make install-skill   fetch the fhe-application-design skill from GitHub into .claude/skills/ and .agents/skills/"
	@echo "  make clean           remove the build tree and all per-run artifacts"
	@echo "  build / run: ./run-in-container.sh \"...\"   (see ./run_test.sh --help)"

# Install the fhe-application-design skill from GitHub into BOTH .claude/skills/
# and .agents/skills/ (Claude Code and the open agent-skills layout), so this is
# not a Claude-only setup. The skill bundles the Docker build context under
# environment/. Both directories are gitignored.
SKILL_REPO ?= https://github.com/NiobiumInc/niobium-skills
SKILL_NAME ?= fhe-application-design
install-skill:
	@tmp=$$(mktemp -d) && git clone --depth 1 $(SKILL_REPO) "$$tmp/ns" && \
	for d in .claude/skills .agents/skills; do \
	  mkdir -p "$$d" && rm -rf "$$d/$(SKILL_NAME)" && \
	  cp -R "$$tmp/ns/skills/$(SKILL_NAME)" "$$d/$(SKILL_NAME)" && \
	  echo "installed skill to $$d/$(SKILL_NAME)"; \
	done; rm -rf "$$tmp"

# Everything a build or a run_test invocation regenerates:
#   build/                       the CMake build tree
#   run_cpu/ run_sim/ run_fog/   per-run client/server homes (keys, ciphertexts)
#   client_home/ server_home/    homes from the README's manual two-process walkthrough
#   dr_server_workload_*/        FHETCH trace / replay directories (e.g. ..._mode_fog)
clean:
	rm -rf build run_cpu run_sim run_sim-full run_fog run_nokey \
	       client_home server_home \
	       dr_server_workload_* nbcc_fhetch_replay_source_*
	@echo "clean: removed the build tree and per-run artifacts"
