#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
#
# Local pipeline orchestrator for the demand-response eligibility app. Reproduces
# the deployment topology on disk (a client home with the secret key, a server
# home WITHOUT it), runs keygen -> encrypt -> server -> decrypt per household,
# and compares the decrypted probability against the faithful twin.
#
#   ./run_test.sh --cpu     plain OpenFHE local validation
#   ./run_test.sh --sim     FHETCH trace -> local fhetch_sim -> compare vs twin
#   ./run_test.sh           (no flag) target the Niobium Fog (needs an API key;
#                           preflights and prints a sign-in pointer if none)
#
# Runs inside the FHE-dev container (invoke via ./run-in-container.sh).
set -euo pipefail

MODE="fog"; FLAG=""
case "${1:-}" in
  --cpu) MODE="cpu"; FLAG="--cpu";;
  --sim) MODE="sim"; FLAG="--sim";;
  "" )   MODE="fog"; FLAG="";;
  *) echo "usage: run_test.sh [--cpu|--sim]"; exit 2;;
esac

# fewer records under --sim: local fhetch_sim replay is the expensive part.
if [ "$MODE" = "sim" ]; then NREC="${NREC:-3}"; else NREC="${NREC:-6}"; fi

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD="$ROOT/build"
INPUTS="$ROOT/data/test_inputs.csv"
TWIN="$ROOT/data/twin_outputs.csv"
TOL_FILE="$ROOT/data/noise_tolerance.txt"
RUN="$ROOT/run_${MODE}"
CLIENT="$RUN/client_home"
SERVER="$RUN/server_home"
RINGCHK="--no-ring-dim-check"   # N = 2^16

rm -rf "$RUN"; mkdir -p "$CLIENT" "$SERVER"
for b in dr_keygen dr_encrypt dr_server dr_decrypt; do
  [ -x "$BUILD/$b" ] || { echo "[FATAL] $BUILD/$b missing — build first"; exit 1; }
done

echo "############ demand-response run_test ($MODE, NREC=$NREC) ############"

# ---- 1. keygen (client home only) -----------------------------------------
t0=$(date +%s.%N)
"$BUILD/dr_keygen" "$CLIENT"
t1=$(date +%s.%N)

# ---- 2. provision server home (NO secret key, NO inputs) -------------------
cp "$CLIENT/cc.bin" "$CLIENT/pk.bin" "$CLIENT/mk.bin" "$CLIENT/rk.bin" "$SERVER/"
cp "$ROOT/model/model.txt" "$SERVER/"
if [ -f "$SERVER/sk.bin" ]; then echo "[FATAL] sk leaked into server home"; exit 1; fi
echo "provisioned server home: $(ls "$SERVER" | tr '\n' ' ')"
echo "  asserted: secret key ABSENT from server home  ✓"

# ---- 3. negative test: server must refuse a secret key in its home ---------
cp "$CLIENT/sk.bin" "$SERVER/sk.bin"
if "$BUILD/dr_server" "$SERVER" $FLAG $RINGCHK >/dev/null 2>&1; then
  echo "[FATAL] server did NOT refuse to start with a secret key present"; rm -f "$SERVER/sk.bin"; exit 1
else
  echo "negative test: server refused to start with sk.bin present  ✓"
fi
rm -f "$SERVER/sk.bin"

# ---- Fog mode: preflight only (no account here) ---------------------------
if [ "$MODE" = "fog" ]; then
  echo; echo "---- Fog preflight (default mode) ----"
  "$BUILD/dr_encrypt" "$CLIENT" "$INPUTS" 0 "$SERVER/ct_x.bin"
  "$BUILD/dr_server" "$SERVER" $RINGCHK || true
  echo "(Provide a Fog API key via 'fog login' or FOG_API_TOKEN to dispatch to the Fog;"
  echo " use --sim for account-free local validation.)"
  exit 0
fi

# ---- 4. per-household pipeline ---------------------------------------------
RESULTS="$RUN/decrypted.csv"; : > "$RESULTS"
srv_secs=0; peak_rss_kb=0
CTX_BYTES=0; CT_IN_BYTES=0; CT_OUT_BYTES=0
KEY_BYTES=$(du -cb "$SERVER/cc.bin" "$SERVER/mk.bin" "$SERVER/rk.bin" "$SERVER/pk.bin" | tail -1 | cut -f1)

for ((i=0; i<NREC; i++)); do
  "$BUILD/dr_encrypt" "$CLIENT" "$INPUTS" "$i" "$CLIENT/ct_x_$i.bin" >/dev/null
  cp "$CLIENT/ct_x_$i.bin" "$SERVER/ct_x.bin"           # only ciphertext crosses
  CT_IN_BYTES=$(stat -c%s "$SERVER/ct_x.bin")

  ts=$(date +%s.%N)
  # Launch the server through a tiny python wrapper so we can read the child's
  # peak resident memory via getrusage(RUSAGE_CHILDREN) — no external `time`.
  rss=$(python3 - "$RUN/server_$i.log" "$BUILD/dr_server" "$SERVER" $FLAG $RINGCHK <<'PY'
import sys, subprocess, resource
log, cmd = sys.argv[1], sys.argv[2:]
with open(log, 'wb') as f:
    rc = subprocess.run(cmd, stdout=f, stderr=subprocess.STDOUT).returncode
kb = resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss
print(kb)
sys.exit(rc)
PY
) || { cat "$RUN/server_$i.log"; exit 1; }
  [ "${rss:-0}" -gt "$peak_rss_kb" ] && peak_rss_kb=$rss
  te=$(date +%s.%N)
  srv_secs=$(awk -v a="$srv_secs" -v s="$ts" -v e="$te" 'BEGIN{print a+(e-s)}')

  CT_OUT_BYTES=$(stat -c%s "$SERVER/ct_result.bin")
  cp "$SERVER/ct_result.bin" "$CLIENT/ct_result_$i.bin"
  "$BUILD/dr_decrypt" "$CLIENT" "$CLIENT/ct_result_$i.bin" "$RUN/prob_$i.txt" >/dev/null
  cat "$RUN/prob_$i.txt" >> "$RESULTS"
  # surface the free ring-level identity check under --sim
  grep -h "ring-level" "$RUN/server_$i.log" || true
done

# ---- 5. compare against the twin ------------------------------------------
python3 - "$RESULTS" "$TWIN" "$TOL_FILE" "$NREC" <<'PY'
import sys
res, twin, tolf, nrec = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])
def probs(path, n):
    out=[]
    for line in open(path):
        line=line.strip()
        if not line or line.startswith('#'): continue
        out.append(float(line.split(',')[0]))
        if len(out)>=n: break
    return out
dec=probs(res, nrec); tw=probs(twin, nrec)
tol=float(open(tolf).read().strip())
errs=[abs(d-t) for d,t in zip(dec,tw)]
flips=sum(1 for d,t in zip(dec,tw) if (d>0.5)!=(t>0.5))
print("\n=== FHE vs faithful twin (encryption-noise cost) ===")
print(f"records compared     : {len(errs)}")
print(f"max |prob FHE-twin|  : {max(errs):.3e}")
print(f"mean|prob FHE-twin|  : {sum(errs)/len(errs):.3e}")
print(f"noise tolerance      : {tol:.3e}  (min twin decision margin)")
print(f"decision flips       : {flips}")
ok = (max(errs) < tol) and (flips==0)
print(f"RESULT               : {'PASS' if ok else 'FAIL'}  "
      f"(max error {'<' if max(errs)<tol else '>='} tolerance, {flips} flips)")
sys.exit(0 if ok else 1)
PY
CMP=$?

echo
echo "=== deployment profile ($MODE) ==="
printf "server wall-clock (%d recs): %.2f s  (%.2f s/record)\n" "$NREC" "$srv_secs" "$(awk -v s="$srv_secs" -v n="$NREC" 'BEGIN{print s/n}')"
printf "peak server RSS            : %d MB\n" "$((peak_rss_kb/1024))"
printf "setup keys (cc+mk+rk+pk)   : %.1f MB (client->server, once)\n" "$(awk -v b="$KEY_BYTES" 'BEGIN{print b/1048576}')"
printf "input ciphertext / request : %.2f MB (client->server)\n" "$(awk -v b="$CT_IN_BYTES" 'BEGIN{print b/1048576}')"
printf "output ciphertext / request: %.2f MB (server->client)\n" "$(awk -v b="$CT_OUT_BYTES" 'BEGIN{print b/1048576}')"
exit $CMP
