#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
#
# Local pipeline orchestrator for the demand-response eligibility app. Reproduces
# the deployment topology on disk (a client home with the secret key, a server
# home WITHOUT it), runs keygen -> encrypt -> server -> decrypt per household,
# and compares the decrypted probability against the faithful twin.
#
#   ./run_test.sh --cpu     plain OpenFHE local validation
#   ./run_test.sh --sim     FHETCH trace -> local fhetch_sim -> compare vs twin
#   ./run_test.sh           (no flag) dispatch to the Niobium Fog: needs an API key
#                           (preflights and prints a sign-in pointer if none), then
#                           runs the server step under `fog submit --target=$FOG_TARGET`
#
# Env: FOG_TARGET  (default FOG — the real Niobium Fog; FOG_TARGET=FUNC_SIM for the HW-free simulator).
#      RINGCHK=--no-ring-dim-check  bypasses the minimum-ring-dim security floor;
#              unnecessary at N=2^16 (the check passes there) — opt in only for a
#              deliberately small ring.
#
# Runs inside the FHE-dev container (invoke via ./run-in-container.sh).
set -euo pipefail

usage() {
  cat <<'EOF'
run_test.sh — demand-response eligibility pipeline
  keygen -> encrypt -> server -> decrypt, then compare the decrypted probability to the faithful twin.

Usage: ./run_test.sh [--cpu | --sim | --sim-full] [--input FILE | --values CSV] [-h]
  Scores ONE household (HOUSEHOLD=<row>, default 0) and returns one result.

Score your own usage instead of the bundled data:
  --input FILE   a .csv/.txt whose rows are 672 comma-separated hourly kWh values
                 (28 days x 24 hours). HOUSEHOLD picks the row.
  --values CSV   the same 672 values passed inline, as one comma-separated string.
  Either way the faithful twin is scored for your series on the fly, so the
  encryption-fidelity check still runs. There is no measured label for your own
  data, so no truth column is shown.
  (no flag)   dispatch to the Niobium Fog (default; needs an API key). Records
              hollow (fast); the Fog reconstructs the real values on replay.
  --cpu       plain-OpenFHE local validation on your CPU
  --sim       hollow record -> replay locally (fhetch_sim) -> compare to the twin.
              A faithful local rehearsal of the (hollow) Fog run.
  --sim-full  real-math record -> replay, plus the ring-level ciphertext-identity
              check against OpenFHE (the thorough ground-truth run). Running --sim
              and --sim-full and comparing them surfaces any hollow-recording divergence.
  -h, --help  show this help

Env:
  FOG_TARGET  Fog target for the default mode (default: FOG, the real Niobium Fog;
              set FOG_TARGET=FUNC_SIM for the hardware-free functional simulator)
  RINGCHK     set to --no-ring-dim-check to bypass the minimum-ring-dim security floor
              (unnecessary at N=2^16; opt in only for a deliberately small ring)
  HOUSEHOLD   which household (row of the input file) to score (default: 0)
  NREC        validation-sweep size (default: 1). The protocol scores one household
              per request; NREC>1 scores that many consecutive households to give the
              FHE-vs-twin gate more samples, each with its own freshly generated keys.

Run everything through ./run-in-container.sh. Fog access: `fog login`, or request an
account at https://console.niobium.co/request-account.
EOF
}

MODE="fog"; FLAG=""; SIMFULL=0; USER_INPUT=""; USER_VALUES=""
while [ $# -gt 0 ]; do
  case "$1" in
    --cpu) MODE="cpu"; FLAG="--cpu";;
    --sim) MODE="sim"; FLAG="--sim";;
    --sim-full) MODE="sim"; FLAG="--sim"; SIMFULL=1;;
    --input) shift; USER_INPUT="${1:?--input needs a file path}";;
    --values) shift; USER_VALUES="${1:?--values needs comma-separated numbers}";;
    -h|--help) usage; exit 0;;
    *) usage; exit 2;;
  esac
  shift
done

FOG_TARGET="${FOG_TARGET:-FOG}"   # required by fog submit; FOG = real Niobium Fog (FUNC_SIM = HW-free sim)

# Hollow record on the Fog default and --sim (fast, mirrors the Fog run); real math on
# --sim-full (so the server's ring-level ciphertext-identity check runs) and --cpu. The
# record pass skips the heavy polynomial math and the replay reconstructs the real result.
HOLLOW_FLAG=""
case "$MODE" in
  fog) HOLLOW_FLAG="--hollow";;
  sim) [ "$SIMFULL" = 1 ] || HOLLOW_FLAG="--hollow";;
esac

# The protocol scores ONE household per request, so that is the default. HOUSEHOLD
# picks which row of the input file to score. NREC>1 runs a validation sweep of
# consecutive households, each with its OWN freshly generated key set.
HOUSEHOLD="${HOUSEHOLD:-0}"
NREC="${NREC:-1}"

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD="$ROOT/build"
INPUTS="$ROOT/data/test_inputs.csv"
OWN_DATA=0                        # 1 when scoring a user-supplied series
TWIN="$ROOT/data/twin_outputs.csv"
TOL_FILE="$ROOT/data/noise_tolerance.txt"
RUN="$ROOT/run_${MODE}"; [ "$SIMFULL" = 1 ] && RUN="$ROOT/run_sim-full"
CLIENT="$RUN/client_home"
SERVER="$RUN/server_home"
# Minimum-ring-dimension check stays ON: it passes at N=2^16 and guards against an
# insecure / hardware-incompatible ring. Opt in to bypass only for a small ring:
#   RINGCHK=--no-ring-dim-check ./run_test.sh ...
RINGCHK="${RINGCHK:-}"

# Clear the per-run home AND the FHETCH trace cache each run, so --sim-full records
# real math (for its ring-level identity check) instead of reusing a hollow --sim trace.
rm -rf "$RUN" "$ROOT"/dr_server_workload_* "$ROOT"/nbcc_fhetch_replay_source_*; mkdir -p "$CLIENT" "$SERVER"
for b in dr_keygen dr_encrypt dr_server dr_decrypt; do
  [ -x "$BUILD/$b" ] || { echo "[FATAL] $BUILD/$b missing — build first"; exit 1; }
done

# ---- data prerequisites ----------------------------------------------------
# Two generators feed this run. model/make_model_and_data.py writes the COMMITTED
# model + datasets (model.txt, test_inputs.csv, test_labels.csv). model/twin.py writes
# the GITIGNORED ledgers this script gates on (twin_outputs.csv, noise_tolerance.txt) —
# regenerated, never committed — so a fresh clone must produce them once before any run.
# Fail early with a clear pointer instead of a raw Python traceback partway through.
for f in "$ROOT/model/model.txt" "$ROOT/model/derivation.txt" "$INPUTS" "$ROOT/data/test_labels.csv"; do
  [ -f "$f" ] || { echo "[FATAL] $f missing — regenerate: python3 model/make_model_and_data.py"; exit 1; }
done
for f in "$TWIN" "$TOL_FILE"; do
  [ -f "$f" ] || { echo "[FATAL] $f missing — generate the twin ledgers first: python3 model/twin.py"; exit 1; }
done

# ---- your own usage data (--input / --values) -------------------------------
if [ -n "$USER_VALUES" ] && [ -n "$USER_INPUT" ]; then
  echo "[FATAL] use --input OR --values, not both"; exit 2
fi
if [ -n "$USER_VALUES" ]; then
  mkdir -p "$RUN"; INPUTS="$RUN/own_input.csv"
  printf '%s\n' "$USER_VALUES" > "$INPUTS"
  OWN_DATA=1; HOUSEHOLD=0
elif [ -n "$USER_INPUT" ]; then
  [ -f "$USER_INPUT" ] || { echo "[FATAL] --input file not found: $USER_INPUT"; exit 1; }
  INPUTS="$USER_INPUT"; OWN_DATA=1
fi

# ---- bounds + shape checks on whatever input we ended up with ---------------
SERIES_LEN=$(awk '$1=="series_len"{print $2}' "$ROOT/model/derivation.txt")
python3 - "$INPUTS" "$HOUSEHOLD" "$NREC" "$SERIES_LEN" <<'PY'
import sys
path, first, nrec, need = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4])
rows = [l.strip() for l in open(path) if l.strip() and not l.startswith('#')]
n = len(rows)
if first < 0 or nrec < 1:
    sys.exit(f"[FATAL] HOUSEHOLD must be >= 0 and NREC >= 1 (got {first}, {nrec})")
if first >= n:
    sys.exit(f"[FATAL] HOUSEHOLD={first} is out of range: {path} has {n} rows (0..{n-1})")
if first + nrec > n:
    sys.exit(f"[FATAL] HOUSEHOLD={first} NREC={nrec} runs past the end: "
             f"{path} has {n} rows, so the most you can score from here is {n-first}")
for k in range(first, first + nrec):
    got = len(rows[k].split(','))
    if got != need:
        sys.exit(f"[FATAL] row {k} of {path} has {got} values, expected {need} "
                 f"(28 days x 24 hourly kWh readings)")
PY

# A user-supplied series has no measured label and no precomputed twin row, so
# score its faithful twin now and compare the encrypted run against that.
if [ "$OWN_DATA" = 1 ]; then
  TWIN="$RUN/own_twin.csv"; mkdir -p "$RUN"; : > "$TWIN"
  for ((k=HOUSEHOLD; k<HOUSEHOLD+NREC; k++)); do
    python3 "$ROOT/model/twin.py" --score "$INPUTS" "$k" >> "$TWIN"
  done
fi

if [ "$NREC" -eq 1 ]; then
  echo "############ demand-response run_test ($MODE, household $HOUSEHOLD) ############"
else
  echo "############ demand-response run_test ($MODE, validation sweep: households $HOUSEHOLD..$((HOUSEHOLD+NREC-1))) ############"
  echo "sweep shortcut: these households share one key set so the sweep stays fast"
fi

# ---- 1. keygen (client home only) -----------------------------------------
t0=$(date +%s.%N)
"$BUILD/dr_keygen" "$CLIENT"
t1=$(date +%s.%N)

# ---- 2. provision server home (NO secret key, NO inputs) -------------------
cp "$CLIENT/cc.bin" "$CLIENT/pk.bin" "$CLIENT/mk.bin" "$CLIENT/rk.bin" "$SERVER/"
# The server gets both layers: the PUBLIC CalTRACK/TOWT derivation and the
# utility's CONFIDENTIAL scoring weights. Neither is ever sent to the client.
cp "$ROOT/model/model.txt" "$ROOT/model/derivation.txt" "$SERVER/"
if [ -f "$SERVER/sk.bin" ]; then echo "[FATAL] sk leaked into server home"; exit 1; fi
echo "provisioned server home: $(ls "$SERVER" | tr '\n' ' ')"
echo "  asserted: secret key ABSENT from server home  ✓"

# ---- 3. negative test: server must refuse a secret key in its home ---------
cp "$CLIENT/sk.bin" "$SERVER/sk.bin"
if "$BUILD/dr_server" "$SERVER" $FLAG $RINGCHK >/dev/null 2>&1; then
  echo "[FATAL] server did NOT refuse to start with a secret key present"; rm -f "$SERVER/sk.bin"; exit 1
else
  echo "negative test: server refused to start with sk.bin present  ✓"
fi
rm -f "$SERVER/sk.bin"

# ---- Fog mode: preflight for an API key, then dispatch (per-household, below) --
if [ "$MODE" = "fog" ]; then
  echo; echo "---- Niobium Fog (default mode) — target=$FOG_TARGET ----"
  if [ ! -f "$HOME/.fog/credentials" ] && [ -z "${FOG_API_TOKEN:-}" ]; then
    echo "No Fog API key found — not dispatching."
    echo "  Have an account?  fog login          (mounts ~/.fog via run-in-container.sh)"
    echo "  New to the Fog?   request access at https://console.niobium.co/request-account"
    echo "  Account-free local validation:  ./run_test.sh --sim"
    exit 0
  fi
  echo "Fog API key found — dispatching the per-household server step under 'fog submit'."
fi

# ---- 4. per-household pipeline ---------------------------------------------
echo
echo "Encrypted scoring is compute-intensive: expect up to a couple of minutes per household."
RESULTS="$RUN/decrypted.csv"; : > "$RESULTS"
srv_secs=0; peak_rss_kb=0
CTX_BYTES=0; CT_IN_BYTES=0; CT_OUT_BYTES=0
KEY_BYTES=$(du -cb "$SERVER/cc.bin" "$SERVER/mk.bin" "$SERVER/rk.bin" "$SERVER/pk.bin" | tail -1 | cut -f1)

for ((j=0; j<NREC; j++)); do
  i=$((HOUSEHOLD + j))
  "$BUILD/dr_encrypt" "$CLIENT" "$INPUTS" "$i" "$CLIENT/ct_x_$i.bin" >/dev/null
  cp "$CLIENT/ct_x_$i.bin" "$SERVER/ct_x.bin"           # only ciphertext crosses
  CT_IN_BYTES=$(stat -c%s "$SERVER/ct_x.bin")

  ts=$(date +%s.%N)
  if [ "$MODE" = "fog" ]; then
    # Dispatch to the Fog. `fog submit <program> <args…> --target=T` provisions a
    # job, wires NBCC_FHETCH_SERVER to the assigned worker, then execs the server
    # with no --cpu/--sim (so replay() dispatches to the Fog); the server
    # reconstructs ct_result.bin locally — identical downstream path to --cpu/--sim.
    # Compute runs on the worker, so local peak RSS is not meaningful here.
    # The Fog runs exactly N=2^16, so the ring-dim guard stays on here (RINGCHK, the local-testing bypass, is not forwarded).
    fog submit "$BUILD/dr_server" "$SERVER" $HOLLOW_FLAG --target="$FOG_TARGET" \
      > "$RUN/server_$i.log" 2>&1 || { cat "$RUN/server_$i.log"; exit 1; }
  else
    # Launch the server through a tiny python wrapper so we can read the child's
    # peak resident memory via getrusage(RUSAGE_CHILDREN) — no external `time`.
    rss=$(python3 - "$RUN/server_$i.log" "$BUILD/dr_server" "$SERVER" $FLAG $RINGCHK $HOLLOW_FLAG <<'PY'
import sys, subprocess, resource
log, cmd = sys.argv[1], sys.argv[2:]
with open(log, 'wb') as f:
    rc = subprocess.run(cmd, stdout=f, stderr=subprocess.STDOUT).returncode
kb = resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss
print(kb)
sys.exit(rc)
PY
) || { cat "$RUN/server_$i.log"; exit 1; }
    [ "${rss:-0}" -gt "$peak_rss_kb" ] && peak_rss_kb=$rss
  fi
  te=$(date +%s.%N)
  srv_secs=$(awk -v a="$srv_secs" -v s="$ts" -v e="$te" 'BEGIN{print a+(e-s)}')

  CT_OUT_BYTES=$(stat -c%s "$SERVER/ct_result.bin")
  cp "$SERVER/ct_result.bin" "$CLIENT/ct_result_$i.bin"
  "$BUILD/dr_decrypt" "$CLIENT" "$CLIENT/ct_result_$i.bin" "$RUN/prob_$i.txt" >/dev/null
  cat "$RUN/prob_$i.txt" >> "$RESULTS"
  # surface the free ring-level identity check under --sim, and the record-pass time
  grep -h "ring-level\|record-pass\|hollow recording" "$RUN/server_$i.log" || true
done

# ---- 5. what each household learned, then the model's offline quality --------
# The protocol scores ONE household per request and returns an answer only that
# household can read. So the run leads with the per-household result, and the
# population figures below are offline model validation on a labeled set.
echo
if [ "$NREC" -eq 1 ]; then echo "=== your result ==="; else echo "=== results (validation sweep) ==="; fi
python3 - "$RESULTS" "$ROOT/data/test_labels.csv" "$HOUSEHOLD" "$NREC" "$OWN_DATA" <<'PY'
import sys
res, lab, first, nrec, own = (sys.argv[1], sys.argv[2], int(sys.argv[3]),
                             int(sys.argv[4]), sys.argv[5] == "1")
probs=[]
for line in open(res):
    line=line.strip()
    if not line or line.startswith('#'): continue
    probs.append(float(line.split(',')[0]))
truth=[]
for line in ([] if own else open(lab)):
    line=line.strip()
    if not line or line.startswith('#'): continue
    try: truth.append(int(line.split(',')[1]))
    except ValueError: continue
def row(k, p):
    ans = "ELIGIBLE" if p > 0.5 else "not eligible"
    if own:
        return ans, None
    return ans, ("eligible" if truth[k] else "not eligible")
if nrec == 1:
    p = probs[0]; ans, t = row(first, p)
    print(f"{'your usage' if own else 'household scored':<24}: "
          f"{'from your own input' if own else first}")
    print(f"eligibility probability : {p:.4f}")
    print(f"your answer             : {ans}")
    if t is not None:
        print(f"measured truth for you  : {t}")
    print("decrypted with your own secret key; the server only ever held ciphertext")
else:
    hdr = f"{'row':>10} {'probability':>12} {'its answer':>15}"
    print(hdr if own else hdr + f" {'measured truth':>16}")
    for j, p in enumerate(probs):
        ans, t = row(first + j, p)
        line = f"{first+j:>10} {p:>12.4f} {ans:>15}"
        print(line if t is None else line + f" {t:>16}")
    print("validation sweep: one key set covers these rows, so this is a test shape, "
          "not the deployment shape")
PY

echo "=== model quality (offline validation on the labeled development set) ==="
python3 - "$ROOT/data/twin_outputs.csv" "$ROOT/data/test_labels.csv" <<'PY'
import sys
twin_path, lab_path = sys.argv[1], sys.argv[2]
probs=[]
for line in open(twin_path):
    line=line.strip()
    if not line or line.startswith('#'): continue
    probs.append(float(line.split(',')[0]))
y=[]
for line in open(lab_path):
    line=line.strip()
    if not line or line.startswith('#'): continue
    try: y.append(int(line.split(',')[1]))
    except ValueError: continue
n=min(len(probs),len(y)); probs=probs[:n]; y=y[:n]
npos=sum(y); base=npos/n
order=sorted(range(n), key=lambda i: probs[i])
ranks=[0.0]*n; i=0
while i<n:
    j=i
    while j+1<n and probs[order[j+1]]==probs[order[i]]: j+=1
    avg=(i+j)/2.0+1.0
    for k in range(i,j+1): ranks[order[k]]=avg
    i=j+1
nneg=n-npos
sumpos=sum(ranks[k] for k in range(n) if y[k]==1)
auc=(sumpos-npos*(npos+1)/2)/(npos*nneg) if npos and nneg else float('nan')
sel=[i for i in range(n) if probs[i]>0.5]
tp=sum(y[i] for i in sel); k=len(sel)
prec=tp/k if k else float('nan'); rec=tp/npos if npos else float('nan')
print(f"households in the set      : {n} (scored in the clear, labels known)")
print(f"base rate                  : {100*base:.1f}% are eligible")
print(f"ROC-AUC                    : {auc:.3f}")
print(f"when it answers ELIGIBLE   : right {100*prec:.1f}% of the time "
      f"({100*base:.1f}% at random, so {prec/base:.2f}x better)")
print(f"of truly eligible households: {100*rec:.1f}% are told so")
PY

# ---- 6. compare against the twin (correctness PASS/FAIL gate) --------------
TWIN_OFFSET="$HOUSEHOLD"; [ "$OWN_DATA" = 1 ] && TWIN_OFFSET=0
python3 - "$RESULTS" "$TWIN" "$TOL_FILE" "$NREC" "$TWIN_OFFSET" <<'PY'
import sys
res, twin, tolf, nrec, first = (sys.argv[1], sys.argv[2], sys.argv[3],
                                int(sys.argv[4]), int(sys.argv[5]))
def probs(path):
    out=[]
    for line in open(path):
        line=line.strip()
        if not line or line.startswith('#'): continue
        out.append(float(line.split(',')[0]))
    return out
dec=probs(res)[:nrec]
tw=probs(twin)[first:first+nrec]        # the SAME households the run scored
tol=float(open(tolf).read().strip())
errs=[abs(d-t) for d,t in zip(dec,tw)]
flips=sum(1 for d,t in zip(dec,tw) if (d>0.5)!=(t>0.5))
print("\n=== encryption fidelity (FHE vs the faithful twin) ===")
print(f"records compared     : {len(errs)}")
print(f"max |prob FHE-twin|  : {max(errs):.3e}")
print(f"mean|prob FHE-twin|  : {sum(errs)/len(errs):.3e}")
print(f"noise tolerance      : {tol:.3e}  (min twin decision margin)")
print(f"decision flips       : {flips}")
ok = (max(errs) < tol) and (flips==0)
print(f"RESULT               : {'PASS' if ok else 'FAIL'}  "
      f"(max error {'<' if max(errs)<tol else '>='} tolerance, {flips} flips)")
sys.exit(0 if ok else 1)
PY
CMP=$?

echo
echo "=== deployment profile ($MODE) ==="
printf "server wall-clock (%d recs): %.2f s  (%.2f s/record)\n" "$NREC" "$srv_secs" "$(awk -v s="$srv_secs" -v n="$NREC" 'BEGIN{print s/n}')"
if [ "$MODE" = "fog" ]; then
  printf "compute location          : Niobium Fog (target=%s; server RSS is remote, not measured)\n" "$FOG_TARGET"
else
  printf "peak server RSS            : %d MB\n" "$((peak_rss_kb/1024))"
fi
printf "setup keys (cc+mk+rk+pk)   : %.1f MB (client->server, once)\n" "$(awk -v b="$KEY_BYTES" 'BEGIN{print b/1048576}')"
printf "input ciphertext / request : %.2f MB (client->server)\n" "$(awk -v b="$CT_IN_BYTES" 'BEGIN{print b/1048576}')"
printf "output ciphertext / request: %.2f MB (server->client)\n" "$(awk -v b="$CT_OUT_BYTES" 'BEGIN{print b/1048576}')"
exit $CMP
