#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
#
# Local pipeline orchestrator for the demand-response eligibility app. Reproduces
# the deployment topology on disk (a client home with the secret key, a server
# home WITHOUT it), runs keygen -> encrypt -> server -> decrypt per household,
# and compares the decrypted probability against the faithful twin.
#
#   ./run_test.sh --cpu     plain OpenFHE local validation
#   ./run_test.sh --sim     FHETCH trace -> local fhetch_sim -> compare vs twin
#   ./run_test.sh           (no flag) dispatch to the Niobium Fog: needs an API key
#                           (preflights and prints a sign-in pointer if none), then
#                           runs the server step under `fog submit --target=$FOG_TARGET`
#
# Env: FOG_TARGET  (default FOG — the real Niobium Fog; FOG_TARGET=FUNC_SIM for the HW-free simulator).
#      RINGCHK=--no-ring-dim-check  bypasses the minimum-ring-dim security floor;
#              unnecessary at N=2^16 (the check passes there) — opt in only for a
#              deliberately small ring.
#
# Runs inside the FHE-dev container (invoke via ./run-in-container.sh).
set -euo pipefail

usage() {
  cat <<'EOF'
run_test.sh — demand-response eligibility pipeline
  keygen -> encrypt -> server -> decrypt, then compare the decrypted probability to the faithful twin.

Usage: ./run_test.sh [--cpu | --sim | -h]
  (no flag)   dispatch to the Niobium Fog (default; needs an API key)
  --cpu       plain-OpenFHE local validation on your CPU
  --sim       record the FHETCH trace and replay it locally (fhetch_sim)
  -h, --help  show this help

Env:
  FOG_TARGET  Fog target for the default mode (default: FOG, the real Niobium Fog;
              set FOG_TARGET=FUNC_SIM for the hardware-free functional simulator)
  RINGCHK     set to --no-ring-dim-check to bypass the minimum-ring-dim security floor
              (unnecessary at N=2^16; opt in only for a deliberately small ring)
  NREC        records to score (default: cpu=6, sim=3, fog=2)

Run everything through ./run-in-container.sh. Fog access: `fog login`, or request an
account at https://console.niobium.co/request-account.
EOF
}

MODE="fog"; FLAG=""
case "${1:-}" in
  --cpu) MODE="cpu"; FLAG="--cpu";;
  --sim) MODE="sim"; FLAG="--sim";;
  "" )   MODE="fog"; FLAG="";;
  -h|--help) usage; exit 0;;
  *) usage; exit 2;;
esac

FOG_TARGET="${FOG_TARGET:-FOG}"   # required by fog submit; FOG = real Niobium Fog (FUNC_SIM = HW-free sim)

# fewer records for the trace paths: each is far heavier per record than plain CPU
# (local fhetch_sim replay under --sim; a provisioned Fog job per household under fog).
case "$MODE" in
  cpu) NREC="${NREC:-6}";;
  sim) NREC="${NREC:-3}";;
  fog) NREC="${NREC:-2}";;
esac

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD="$ROOT/build"
INPUTS="$ROOT/data/test_inputs.csv"
TWIN="$ROOT/data/twin_outputs.csv"
TOL_FILE="$ROOT/data/noise_tolerance.txt"
RUN="$ROOT/run_${MODE}"
CLIENT="$RUN/client_home"
SERVER="$RUN/server_home"
# Minimum-ring-dimension check stays ON: it passes at N=2^16 and guards against an
# insecure / hardware-incompatible ring. Opt in to bypass only for a small ring:
#   RINGCHK=--no-ring-dim-check ./run_test.sh ...
RINGCHK="${RINGCHK:-}"

rm -rf "$RUN"; mkdir -p "$CLIENT" "$SERVER"
for b in dr_keygen dr_encrypt dr_server dr_decrypt; do
  [ -x "$BUILD/$b" ] || { echo "[FATAL] $BUILD/$b missing — build first"; exit 1; }
done

echo "############ demand-response run_test ($MODE, NREC=$NREC) ############"

# ---- 1. keygen (client home only) -----------------------------------------
t0=$(date +%s.%N)
"$BUILD/dr_keygen" "$CLIENT"
t1=$(date +%s.%N)

# ---- 2. provision server home (NO secret key, NO inputs) -------------------
cp "$CLIENT/cc.bin" "$CLIENT/pk.bin" "$CLIENT/mk.bin" "$CLIENT/rk.bin" "$SERVER/"
cp "$ROOT/model/model.txt" "$SERVER/"
if [ -f "$SERVER/sk.bin" ]; then echo "[FATAL] sk leaked into server home"; exit 1; fi
echo "provisioned server home: $(ls "$SERVER" | tr '\n' ' ')"
echo "  asserted: secret key ABSENT from server home  ✓"

# ---- 3. negative test: server must refuse a secret key in its home ---------
cp "$CLIENT/sk.bin" "$SERVER/sk.bin"
if "$BUILD/dr_server" "$SERVER" $FLAG $RINGCHK >/dev/null 2>&1; then
  echo "[FATAL] server did NOT refuse to start with a secret key present"; rm -f "$SERVER/sk.bin"; exit 1
else
  echo "negative test: server refused to start with sk.bin present  ✓"
fi
rm -f "$SERVER/sk.bin"

# ---- Fog mode: preflight for an API key, then dispatch (per-household, below) --
if [ "$MODE" = "fog" ]; then
  echo; echo "---- Niobium Fog (default mode) — target=$FOG_TARGET ----"
  if [ ! -f "$HOME/.fog/credentials" ] && [ -z "${FOG_API_TOKEN:-}" ]; then
    echo "No Fog API key found — not dispatching."
    echo "  Have an account?  fog login          (mounts ~/.fog via run-in-container.sh)"
    echo "  New to the Fog?   request access at https://console.niobium.co/request-account"
    echo "  Account-free local validation:  ./run_test.sh --sim"
    exit 0
  fi
  echo "Fog API key found — dispatching the per-household server step under 'fog submit'."
fi

# ---- 4. per-household pipeline ---------------------------------------------
RESULTS="$RUN/decrypted.csv"; : > "$RESULTS"
srv_secs=0; peak_rss_kb=0
CTX_BYTES=0; CT_IN_BYTES=0; CT_OUT_BYTES=0
KEY_BYTES=$(du -cb "$SERVER/cc.bin" "$SERVER/mk.bin" "$SERVER/rk.bin" "$SERVER/pk.bin" | tail -1 | cut -f1)

for ((i=0; i<NREC; i++)); do
  "$BUILD/dr_encrypt" "$CLIENT" "$INPUTS" "$i" "$CLIENT/ct_x_$i.bin" >/dev/null
  cp "$CLIENT/ct_x_$i.bin" "$SERVER/ct_x.bin"           # only ciphertext crosses
  CT_IN_BYTES=$(stat -c%s "$SERVER/ct_x.bin")

  ts=$(date +%s.%N)
  if [ "$MODE" = "fog" ]; then
    # Dispatch to the Fog. `fog submit <program> <args…> --target=T` provisions a
    # job, wires NBCC_FHETCH_SERVER to the assigned worker, then execs the server
    # with no --cpu/--sim (so replay() dispatches to the Fog); the server
    # reconstructs ct_result.bin locally — identical downstream path to --cpu/--sim.
    # Compute runs on the worker, so local peak RSS is not meaningful here.
    fog submit "$BUILD/dr_server" "$SERVER" $RINGCHK --target="$FOG_TARGET" \
      > "$RUN/server_$i.log" 2>&1 || { cat "$RUN/server_$i.log"; exit 1; }
  else
    # Launch the server through a tiny python wrapper so we can read the child's
    # peak resident memory via getrusage(RUSAGE_CHILDREN) — no external `time`.
    rss=$(python3 - "$RUN/server_$i.log" "$BUILD/dr_server" "$SERVER" $FLAG $RINGCHK <<'PY'
import sys, subprocess, resource
log, cmd = sys.argv[1], sys.argv[2:]
with open(log, 'wb') as f:
    rc = subprocess.run(cmd, stdout=f, stderr=subprocess.STDOUT).returncode
kb = resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss
print(kb)
sys.exit(rc)
PY
) || { cat "$RUN/server_$i.log"; exit 1; }
    [ "${rss:-0}" -gt "$peak_rss_kb" ] && peak_rss_kb=$rss
  fi
  te=$(date +%s.%N)
  srv_secs=$(awk -v a="$srv_secs" -v s="$ts" -v e="$te" 'BEGIN{print a+(e-s)}')

  CT_OUT_BYTES=$(stat -c%s "$SERVER/ct_result.bin")
  cp "$SERVER/ct_result.bin" "$CLIENT/ct_result_$i.bin"
  "$BUILD/dr_decrypt" "$CLIENT" "$CLIENT/ct_result_$i.bin" "$RUN/prob_$i.txt" >/dev/null
  cat "$RUN/prob_$i.txt" >> "$RESULTS"
  # surface the free ring-level identity check under --sim
  grep -h "ring-level" "$RUN/server_$i.log" || true
done

# ---- 5. application quality (LEAD: real accuracy/AUC vs the TRUE labels) ----
# The model is FITTED to an independent Bernoulli-sampled label with a documented
# base rate, so its quality is genuinely measurable. These are the fitted model's
# predictions vs the TRUE labels over the full labeled test set. The per-household
# prediction is exactly the function the encrypted circuit evaluates (the faithful
# twin); the encrypted run reproduces it to ~1e-7 — certified on the sampled
# households by the FHE-vs-twin fidelity gate immediately below.
echo
echo "=== application quality (fitted model vs true labels, labeled test set) ==="
python3 - "$TWIN" "$ROOT/data/test_labels.csv" "$NREC" <<'PY'
import sys
twin_path, lab_path, nrec = sys.argv[1], sys.argv[2], int(sys.argv[3])
probs=[]
for line in open(twin_path):
    line=line.strip()
    if not line or line.startswith('#'): continue
    probs.append(float(line.split(',')[0]))
y=[]
for line in open(lab_path):
    line=line.strip()
    if not line or line.startswith('#'): continue
    try: y.append(int(line.split(',')[1]))
    except ValueError: continue   # skip the CSV header row
n=min(len(probs),len(y)); probs=probs[:n]; y=y[:n]
pred=[1 if p>0.5 else 0 for p in probs]
base=sum(y)/n
acc=sum(1 for p,t in zip(pred,y) if p==t)/n
# ROC-AUC via average-rank of the positive class (tie-aware Mann-Whitney).
order=sorted(range(n), key=lambda i: probs[i])
ranks=[0.0]*n; i=0
while i<n:
    j=i
    while j+1<n and probs[order[j+1]]==probs[order[i]]: j+=1
    avg=(i+j)/2.0+1.0
    for k in range(i,j+1): ranks[order[k]]=avg
    i=j+1
npos=sum(y); nneg=n-npos
sumpos=sum(ranks[k] for k in range(n) if y[k]==1)
auc=(sumpos-npos*(npos+1)/2)/(npos*nneg) if npos and nneg else float('nan')
tp=sum(1 for p,t in zip(pred,y) if p==1 and t==1)
fp=sum(1 for p,t in zip(pred,y) if p==1 and t==0)
fn=sum(1 for p,t in zip(pred,y) if p==0 and t==1)
prec=tp/(tp+fp) if tp+fp else 0.0
rec=tp/(tp+fn) if tp+fn else 0.0
f1=2*prec*rec/(prec+rec) if prec+rec else 0.0
print(f"labeled test households    : {n}")
print(f"base rate (true labels)    : {100*base:.1f}% eligible")
print(f"accuracy                   : {acc:.3f}")
print(f"ROC-AUC                    : {auc:.3f}")
print(f"precision / recall / F1    : {prec:.3f} / {rec:.3f} / {f1:.3f}  (positive = eligible)")
print(f"summary                    : base rate {100*base:.0f}% eligible; accuracy {acc:.2f}, AUC {auc:.2f}")
print(f"(predictions the encrypted run reproduces; fidelity certified below on the "
      f"{nrec}-household encrypted sample)")
PY

# ---- 6. compare against the twin (correctness PASS/FAIL gate) --------------
python3 - "$RESULTS" "$TWIN" "$TOL_FILE" "$NREC" <<'PY'
import sys
res, twin, tolf, nrec = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])
def probs(path, n):
    out=[]
    for line in open(path):
        line=line.strip()
        if not line or line.startswith('#'): continue
        out.append(float(line.split(',')[0]))
        if len(out)>=n: break
    return out
dec=probs(res, nrec); tw=probs(twin, nrec)
tol=float(open(tolf).read().strip())
errs=[abs(d-t) for d,t in zip(dec,tw)]
flips=sum(1 for d,t in zip(dec,tw) if (d>0.5)!=(t>0.5))
print("\n=== encryption fidelity (FHE vs the faithful twin) ===")
print(f"records compared     : {len(errs)}")
print(f"max |prob FHE-twin|  : {max(errs):.3e}")
print(f"mean|prob FHE-twin|  : {sum(errs)/len(errs):.3e}")
print(f"noise tolerance      : {tol:.3e}  (min twin decision margin)")
print(f"decision flips       : {flips}")
ok = (max(errs) < tol) and (flips==0)
print(f"RESULT               : {'PASS' if ok else 'FAIL'}  "
      f"(max error {'<' if max(errs)<tol else '>='} tolerance, {flips} flips)")
sys.exit(0 if ok else 1)
PY
CMP=$?

echo
echo "=== deployment profile ($MODE) ==="
printf "server wall-clock (%d recs): %.2f s  (%.2f s/record)\n" "$NREC" "$srv_secs" "$(awk -v s="$srv_secs" -v n="$NREC" 'BEGIN{print s/n}')"
if [ "$MODE" = "fog" ]; then
  printf "compute location          : Niobium Fog (target=%s; server RSS is remote, not measured)\n" "$FOG_TARGET"
else
  printf "peak server RSS            : %d MB\n" "$((peak_rss_kb/1024))"
fi
printf "setup keys (cc+mk+rk+pk)   : %.1f MB (client->server, once)\n" "$(awk -v b="$KEY_BYTES" 'BEGIN{print b/1048576}')"
printf "input ciphertext / request : %.2f MB (client->server)\n" "$(awk -v b="$CT_IN_BYTES" 'BEGIN{print b/1048576}')"
printf "output ciphertext / request: %.2f MB (server->client)\n" "$(awk -v b="$CT_OUT_BYTES" 'BEGIN{print b/1048576}')"
exit $CMP
