#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
# Trust-boundary guard: refuse to launch the server if a secret key is present
# in the server home (the current directory). dr_server already aborts on a
# secret key in its home (exit 3); this runtime guard is the belt-and-suspenders
# check a reviewer can exercise (plant a key, watch the refusal) and the one the
# two-process demo runs the server behind.
if [ -f sk.bin ] || [ -f keys/sk.bin ] || [ -f secret_key.bin ] || [ -f keys/secret_key.bin ]; then
  echo "[server-guard] REFUSING to start: a secret key is present in the server home" >&2
  exit 13
fi
exec "$@"
