# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
"""
Two-process client/server demo (the deployment-shaped run).

Client and server run as SEPARATE OS processes communicating only over HTTP,
exchanging serialized ciphertext — never keys-that-decrypt, never plaintext.

  server process (run_demo/server_home) — the utility / compute provider:
    - REFUSES to start if a secret key is present in its home (exit 13)
    - setup endpoint receives the crypto context + public/eval keys, and holds
      the utility's own two model layers: the PUBLIC CalTRACK/TOWT derivation
      (derivation.txt) and its CONFIDENTIAL weights (model.txt), which are
      never disclosed to the household
    - runs the generated `dr_server` binary (--cpu) on the encrypted household
    - logs ONLY byte counts — it never sees (and cannot see) a usage profile
      or an eligibility score
  client process (run_demo/client_home) — the household / biobank:
    - generates all keys with `dr_keygen`; the secret key (sk.bin) NEVER
      crosses the wire
    - encrypts one household's 28-day hourly series per request, uploads the
      ciphertext, downloads the encrypted result, decrypts, prints the
      eligibility probability

Only ciphertext (and, at setup, the context + public/eval keys + model) crosses
the wire. Point the client at a remote host with SERVER_URL=http://host:port —
the server home is safe to copy to an untrusted machine as-is.

Usage (inside the container):  python3 harness/demo_two_process.py
Env: DEMO_PORT (default 8471), SERVER_URL, DEMO_NREC (households to score, default 3).
"""

import http.server
import os
import shutil
import subprocess
import sys
import threading
import time
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "build")          # C++ four-program build tree (not nb_out/build)
RUN = os.path.join(ROOT, "run_demo")
CLIENT = os.path.join(RUN, "client_home")
SERVER = os.path.join(RUN, "server_home")
INPUTS = os.path.join(ROOT, "data", "test_inputs.csv")
TWIN = os.path.join(ROOT, "data", "twin_outputs.csv")
PORT = int(os.environ.get("DEMO_PORT", "8471"))
SERVER_URL = os.environ.get("SERVER_URL", f"http://127.0.0.1:{PORT}")
NREC = int(os.environ.get("DEMO_NREC", "3"))  # households to score in the demo

# The crypto context + public/eval keys + public model the utility needs. These
# are exactly what run_test.sh provisions into the server home (never sk.bin).
SETUP_KEYS = ("cc.bin", "pk.bin", "mk.bin", "rk.bin")

# Any of these in the server home is a secret key and must block the server.
SECRET_KEY_NAMES = ("sk.bin", "keys/sk.bin", "secret_key.bin", "keys/secret_key.bin")


def run(cmd, cwd):
    # The binaries carry an rpath to the OpenFHE shared libs (CMake
    # BUILD_RPATH_USE_ORIGIN), so — like run_test.sh — no LD_LIBRARY_PATH is set.
    subprocess.run(cmd, cwd=cwd, check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def has_secret_key(home):
    return any(os.path.exists(os.path.join(home, p)) for p in SECRET_KEY_NAMES)


# ---------------------------------------------------------------- server ---
class ServerHandler(http.server.BaseHTTPRequestHandler):
    """The untrusted compute provider. Sees bytes in, bytes out."""

    def log_message(self, fmt, *args):  # quiet the default access log
        pass

    def do_PUT(self):
        # receive a file into the server home (setup keys / model / input ciphertext)
        rel = self.path.lstrip("/")
        dest = os.path.normpath(os.path.join(SERVER, rel))
        assert dest.startswith(SERVER), "path escape"
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        n = int(self.headers["Content-Length"])
        with open(dest, "wb") as fh:
            remaining = n
            while remaining:
                chunk = self.rfile.read(min(1 << 20, remaining))
                fh.write(chunk)
                remaining -= len(chunk)
        print(f"[server] received {n:>12,} bytes -> {rel}  (opaque to me)")
        self.send_response(200)
        self.end_headers()

    def do_POST(self):
        # /score — run dr_server (--cpu) on the household ciphertext in my home
        t0 = time.time()
        run([os.path.join(ROOT, "server_guard.sh"),
             os.path.join(BUILD, "dr_server"), SERVER, "--cpu"], cwd=SERVER)
        dt = time.time() - t0
        out = os.path.join(SERVER, "ct_result.bin")
        data = open(out, "rb").read()
        print(f"[server] scored one household in {dt:.1f}s; returning "
              f"{len(data):,} bytes, still encrypted — I never saw a usage "
              f"profile or a score")
        self.send_response(200)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)


def start_server():
    # The runtime trust guard: refuse to serve if a secret key is present.
    if has_secret_key(SERVER):
        print("[server] REFUSING to start: secret key found in server home",
              file=sys.stderr)
        sys.exit(13)
    httpd = http.server.HTTPServer(("127.0.0.1", PORT), ServerHandler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    print(f"[server] compute provider listening on {SERVER_URL} "
          f"(home: {SERVER})")
    return httpd


# ---------------------------------------------------------------- client ---
def put(rel, path):
    with open(path, "rb") as fh:
        data = fh.read()
    req = urllib.request.Request(f"{SERVER_URL}/{rel}", data=data,
                                 method="PUT")
    urllib.request.urlopen(req).read()


def read_prob(path):
    # dr_decrypt writes "<prob>,<eligible>\n"
    line = open(path).read().strip()
    return float(line.split(",")[0])


def load_twin(n):
    if not os.path.exists(TWIN):
        # twin_outputs.csv is a generated ledger; reproduce it from the
        # committed model + inputs (no encryption, a few seconds).
        print("[demo] data/twin_outputs.csv missing — regenerating via "
              "model/twin.py")
        subprocess.run([sys.executable, os.path.join(ROOT, "model", "twin.py")],
                       cwd=ROOT, check=True, stdout=subprocess.DEVNULL)
    out = []
    for line in open(TWIN):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        out.append(float(line.split(",")[0]))
        if len(out) >= n:
            break
    return out


def client_flow():
    print("[client] generating keys (secret key sk.bin stays in my home)")
    run([os.path.join(BUILD, "dr_keygen"), CLIENT], cwd=CLIENT)

    # The client uploads only the crypto context and public/eval keys. The two
    # model layers belong to the UTILITY and are staged here purely because this
    # demo runs both sides on one machine; in a deployment the server already
    # holds them and the household never sees model.txt at all.
    print("[client] SETUP upload: crypto context + public/eval keys "
          "(no secret key crosses the wire)")
    for f in SETUP_KEYS:
        put(f, os.path.join(CLIENT, f))
    print("[setup]  staging the utility's own model files on the server "
          "(public derivation + confidential weights)")
    put("derivation.txt", os.path.join(ROOT, "model", "derivation.txt"))
    put("model.txt", os.path.join(ROOT, "model", "model.txt"))

    probs = []
    for i in range(NREC):
        print(f"[client] encrypting household row {i} (28-day hourly kWh series)")
        ct = os.path.join(CLIENT, f"ct_x_{i}.bin")
        run([os.path.join(BUILD, "dr_encrypt"), CLIENT, INPUTS, str(i), ct],
            cwd=CLIENT)
        put("ct_x.bin", ct)                       # the wire: ciphertext only

        print(f"[client] requesting encrypted scoring for household {i}")
        req = urllib.request.Request(f"{SERVER_URL}/score", method="POST")
        data = urllib.request.urlopen(req, timeout=1200).read()
        result = os.path.join(CLIENT, f"ct_result_{i}.bin")
        with open(result, "wb") as fh:
            fh.write(data)
        print(f"[client] received {len(data):,} encrypted bytes; decrypting "
              f"with MY secret key")
        prob_txt = os.path.join(CLIENT, f"prob_{i}.txt")
        run([os.path.join(BUILD, "dr_decrypt"), CLIENT, result, prob_txt],
            cwd=CLIENT)
        probs.append(read_prob(prob_txt))

    twin = load_twin(NREC)
    n = min(len(probs), len(twin))
    worst = max(abs(p - t) for p, t in zip(probs[:n], twin[:n])) if n else 0.0
    print(f"[client] eligibility probabilities: "
          f"{[round(p, 4) for p in probs]}")
    print(f"[client] decisions: "
          f"{['ELIGIBLE' if p > 0.5 else 'not eligible' for p in probs]}")
    print(f"[client] agreement with the faithful twin: max |delta| "
          f"{worst:.3e} over {n} households")


def main():
    # provision the two homes
    shutil.rmtree(RUN, ignore_errors=True)
    os.makedirs(CLIENT)
    os.makedirs(SERVER)

    print("=" * 72)
    print("Two-process demo: household client and untrusted utility/compute "
          "provider, ciphertext-only wire")
    print("=" * 72)

    for b in ("dr_keygen", "dr_encrypt", "dr_server", "dr_decrypt"):
        if not os.access(os.path.join(BUILD, b), os.X_OK):
            print(f"[FATAL] {os.path.join(BUILD, b)} missing — build first "
                  f"(see README 'Run it')", file=sys.stderr)
            sys.exit(1)

    # negative test first: plant a secret key, prove the server refuses
    plant = os.path.join(SERVER, "sk.bin")
    open(plant, "wb").write(b"planted")
    r = subprocess.run([sys.executable, __file__, "--server-only"],
                       capture_output=True, text=True)
    assert r.returncode == 13, "server must refuse a planted secret key"
    print("[demo] negative test: server refused to start with a planted "
          "secret key (exit 13)")
    os.remove(plant)

    start_server()
    time.sleep(0.3)
    client_flow()
    print("[demo] done — the provider handled only ciphertext throughout.")


if __name__ == "__main__":
    if "--server-only" in sys.argv:
        # used by the negative test: start (and refuse) without a client
        if has_secret_key(SERVER):
            print("[server] REFUSING to start: secret key found in server "
                  "home", file=sys.stderr)
            sys.exit(13)
        sys.exit(0)
    main()
