// Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
//
// decrypt (client) — reads the secret key and the result ciphertext, decrypts
// slot 0 (the eligibility probability), applies the reference decision rule
// (prob > 0.5 => eligible), and prints/records the result.
//
// Usage: ./dr_decrypt <client_home> <ct_result.bin> [out_prob.txt]
#include "openfhe.h"
#include <iostream>

#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

using namespace lbcrypto;

int main(int argc, char* argv[]) {
    if (argc < 3) { std::cerr << "usage: dr_decrypt <client_home> <ct_result.bin> [out.txt]\n"; return 2; }
    std::string home = argv[1], ctpath = argv[2];

    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile(home + "/cc.bin", cc, SerType::BINARY))
        throw std::runtime_error("load cc failed");
    PrivateKey<DCRTPoly> sk;
    if (!Serial::DeserializeFromFile(home + "/sk.bin", sk, SerType::BINARY))
        throw std::runtime_error("load sk failed");
    Ciphertext<DCRTPoly> ct;
    if (!Serial::DeserializeFromFile(ctpath, ct, SerType::BINARY))
        throw std::runtime_error("load result failed");

    Plaintext pt;
    cc->Decrypt(sk, ct, &pt);
    pt->SetLength(1);
    double prob = pt->GetRealPackedValue()[0];
    int eligible = (prob > 0.5) ? 1 : 0;

    std::cout << "eligibility probability = " << prob
              << "  ->  " << (eligible ? "ELIGIBLE" : "not eligible") << std::endl;

    if (argc > 3) {
        std::ofstream o(argv[3]);
        o << prob << "," << eligible << "\n";
    }
    return 0;
}
