// Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
//
// encrypt (client) reads ONE household's hourly kWh series, packs it
// into the low slots of a single ciphertext, encrypts under the public key, and
// serializes the ciphertext (the only private data that crosses to the server).
//
// This is the per-record pattern: one household == one ciphertext (independent
// encryptors; SIMD slots beyond the series length are unused).
//
// Usage: ./dr_encrypt <client_home> <inputs_csv> <row_index> <out_ct.bin>
#include "openfhe.h"
#include <fstream>
#include <iostream>
#include <sstream>
#include <vector>

#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

using namespace lbcrypto;

static std::vector<double> read_row(const std::string& path, int idx) {
    std::ifstream f(path);
    if (!f.is_open()) throw std::runtime_error("Cannot open inputs: " + path);
    std::string line;
    int row = 0;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        if (row == idx) {
            std::vector<double> v;
            std::stringstream ss(line);
            std::string tok;
            while (std::getline(ss, tok, ',')) v.push_back(std::stod(tok));
            if (v.empty()) throw std::runtime_error("empty input row " + std::to_string(idx));
            return v;
        }
        ++row;
    }
    throw std::runtime_error("row index out of range: " + std::to_string(idx));
}

int main(int argc, char* argv[]) {
    if (argc < 5) { std::cerr << "usage: dr_encrypt <client_home> <inputs_csv> <row> <out_ct.bin>\n"; return 2; }
    std::string home = argv[1], csv = argv[2], out = argv[4];
    int idx = std::stoi(argv[3]);

    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile(home + "/cc.bin", cc, SerType::BINARY))
        throw std::runtime_error("load cc failed");
    PublicKey<DCRTPoly> pk;
    if (!Serial::DeserializeFromFile(home + "/pk.bin", pk, SerType::BINARY))
        throw std::runtime_error("load pk failed");

    // The household's hourly kWh baseline series. The client needs NOTHING from
    // the utility (no weights, no derivation) to encrypt: it packs its own meter
    // data and ships it. Slots past the series length stay zero, which is what
    // makes the server's rotate-and-sum window safe.
    auto profile = read_row(csv, idx);
    auto pt = cc->MakeCKKSPackedPlaintext(profile);
    auto ct = cc->Encrypt(pk, pt);

    if (!Serial::SerializeToFile(out, ct, SerType::BINARY))
        throw std::runtime_error("serialize ciphertext failed");
    std::cout << "encrypted household row " << idx << " (" << profile.size()
              << " hourly values) -> " << out << std::endl;
    return 0;
}
