// Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
//
// keygen (client) — generates the CKKS crypto context and all keys, and
// serializes them into the CLIENT home. The secret key (sk.bin) is written
// ONLY here; run_test / the two-process demo provision the server home without
// it. The public + evaluation keys (pk/mk/rk) are the ones shipped to the
// server.
//
// Usage: ./dr_keygen <client_home>
#include "openfhe.h"
#include <filesystem>
#include <iostream>

#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

using namespace lbcrypto;

int main(int argc, char* argv[]) {
    std::string home = (argc > 1) ? argv[1] : "client_home";
    std::filesystem::create_directories(home);

    // --- CKKS parameters (Stage 6) -----------------------------------------
    // depth 12 / scaling 50 / first 55, N = 2^16 (backend floor), 128-bit.
    // logQ ~= 55 + 12*50 = 655 -> N = 2^16 required for HEStd_128_classic.
    CCParams<CryptoContextCKKSRNS> parameters;
    parameters.SetSecurityLevel(HEStd_128_classic);
    parameters.SetRingDim(1 << 16);          // 65536 -- set explicitly, do not infer
    parameters.SetMultiplicativeDepth(12);
    parameters.SetScalingModSize(50);
    parameters.SetFirstModSize(55);
    parameters.SetScalingTechnique(FLEXIBLEAUTO);

    CryptoContext<DCRTPoly> cc = GenCryptoContext(parameters);
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    cc->Enable(ADVANCEDSHE);                  // EvalLogistic (Chebyshev)

    std::cout << "=== demand-response keygen (client) ===" << std::endl;
    std::cout << "Ring dimension : " << cc->GetRingDimension() << std::endl;
    std::cout << "Slots          : " << cc->GetEncodingParams()->GetBatchSize() << std::endl;

    auto keyPair = cc->KeyGen();
    cc->EvalMultKeyGen(keyPair.secretKey);                     // relinearization (sigmoid squarings)
    cc->EvalRotateKeyGen(keyPair.secretKey, {1, 2, 4, 8, 16}); // rotate-and-sum (window 32)

    // crypto context + public/eval keys -> ship to server
    if (!Serial::SerializeToFile(home + "/cc.bin", cc, SerType::BINARY))
        throw std::runtime_error("serialize cc failed");
    if (!Serial::SerializeToFile(home + "/pk.bin", keyPair.publicKey, SerType::BINARY))
        throw std::runtime_error("serialize pk failed");
    {
        std::ofstream mk(home + "/mk.bin", std::ios::binary);
        if (!cc->SerializeEvalMultKey(mk, SerType::BINARY)) throw std::runtime_error("serialize mk failed");
    }
    {
        std::ofstream rk(home + "/rk.bin", std::ios::binary);
        if (!cc->SerializeEvalAutomorphismKey(rk, SerType::BINARY)) throw std::runtime_error("serialize rk failed");
    }
    // secret key -> stays on the client, NEVER shipped to the server
    if (!Serial::SerializeToFile(home + "/sk.bin", keyPair.secretKey, SerType::BINARY))
        throw std::runtime_error("serialize sk failed");

    std::cout << "Wrote cc/pk/mk/rk/sk to " << home << "/  (sk.bin stays client-side)" << std::endl;
    return 0;
}
