// Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
//
// server (utility) — runs the encrypted eligibility circuit on the household's
// ciphertext. Never sees plaintext and never holds the secret key.
//
// Run modes (Stage 8 / Stage 10), all evaluating the SAME run_circuit():
//   --cpu   plain OpenFHE, serialize the result ciphertext directly.
//   --sim   record a FHETCH trace, reconstruct the result via local fhetch_sim.
//   (none)  the Fog: record + dispatch the trace to the Niobium Fog (needs an
//           API key; preflights and prints a sign-in pointer if none is found).
//
// Usage: ./dr_server <server_home> [--cpu|--sim] [--no-ring-dim-check]
#include "openfhe.h"
#include "niobium/compiler.h"
#include "../common.hpp"

#include <cstdlib>
#include <filesystem>
#include <iostream>

#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

using namespace lbcrypto;
namespace fs = std::filesystem;

enum class Mode { CPU, SIM, FOG };

static bool fog_key_present() {
    if (const char* t = std::getenv("FOG_API_TOKEN"); t && *t) return true;
    if (const char* h = std::getenv("HOME"); h && *h)
        if (fs::exists(std::string(h) + "/.fog/credentials")) return true;
    return false;
}

static void print_fog_pointer() {
    std::cout <<
      "\nThis program runs on the Niobium Fog and needs an API key, but none was found.\n"
      "  • Sign in:  fog login                                   (mints a key from your account)\n"
      "  • Sign up:  https://console.niobium.co/request-account\n"
      "  • No account yet? Validate locally instead:   dr_server <home> --sim\n" << std::endl;
}

int main(int argc, char* argv[]) {
    // ---- parse our own flags (leave the rest for compiler().init) ----------
    Mode mode = Mode::FOG;
    std::string home = "server_home";
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--cpu") mode = Mode::CPU;
        else if (a == "--sim") mode = Mode::SIM;
        else if (a.rfind("--", 0) == 0) { /* e.g. --no-ring-dim-check: for compiler */ }
        else home = a;
    }

    // ---- trust-boundary guard: the server must never hold a secret key -----
    if (fs::exists(home + "/sk.bin")) {
        std::cerr << "[FATAL] secret key present in server home (" << home
                  << "/sk.bin). The server must run without the secret key. Aborting.\n";
        return 3;
    }

    // ---- Fog preflight (default mode) --------------------------------------
    // No silent fall-back to the local simulator (the skill forbids it): the
    // default mode dispatches to the Niobium Fog and only proceeds when it is
    // actually launched under `fog submit` (which wires NBCC_FHETCH_SERVER to a
    // provisioned worker). Without a key we print the sign-in pointer; with a
    // key but outside `fog submit` we say how to dispatch. Local validation is
    // --sim / --cpu.
    if (mode == Mode::FOG) {
        if (!fog_key_present()) { print_fog_pointer(); return 0; }
        if (std::getenv("NBCC_FHETCH_SERVER") == nullptr) {
            std::cout << "\nFog API key found. To dispatch this workload to the Niobium Fog, launch\n"
                         "the server step under `fog submit` (run_test does this in the default mode).\n"
                         "Account-free local validation: dr_server <home> --sim  (or --cpu).\n" << std::endl;
            return 0;
        }
        // else: running under `fog submit` -> fall through to record + dispatch.
    }

    std::cout << "=== demand-response server ("
              << (mode == Mode::CPU ? "--cpu" : mode == Mode::SIM ? "--sim" : "Fog")
              << ") ===" << std::endl;
    std::cout << "server home: " << home << std::endl;

    // ---- load context, keys, model, input ----------------------------------
    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile(home + "/cc.bin", cc, SerType::BINARY))
        throw std::runtime_error("load cc failed");
    {
        std::ifstream mk(home + "/mk.bin", std::ios::binary);
        if (mk.is_open() && !cc->DeserializeEvalMultKey(mk, SerType::BINARY))
            throw std::runtime_error("load mk failed");
    }
    {
        std::ifstream rk(home + "/rk.bin", std::ios::binary);
        if (rk.is_open() && !cc->DeserializeEvalAutomorphismKey(rk, SerType::BINARY))
            throw std::runtime_error("load rk failed");
    }
    Model model = load_model(home + "/model.txt");
    Ciphertext<DCRTPoly> ct_x;
    if (!Serial::DeserializeFromFile(home + "/ct_x.bin", ct_x, SerType::BINARY))
        throw std::runtime_error("load ct_x failed");
    std::cout << "received " << fs::file_size(home + "/ct_x.bin")
              << " bytes of ciphertext (still encrypted)" << std::endl;

    CircuitPlaintexts pts = build_plaintexts(cc, model);

    // ---- CPU path: plain OpenFHE ------------------------------------------
    if (mode == Mode::CPU) {
        auto prob = run_circuit(cc, model, pts, ct_x);
        if (!Serial::SerializeToFile(home + "/ct_result.bin", prob, SerType::BINARY))
            throw std::runtime_error("serialize result failed");
        std::cout << "returned " << fs::file_size(home + "/ct_result.bin")
                  << " bytes (still encrypted) -> ct_result.bin" << std::endl;
        return 0;
    }

    // ---- Recording path: --sim (local fhetch_sim) or Fog (default) --------
    niobium::compiler().init(argc, argv);
    niobium::compiler().set_program_info("dr_server", "1.0",
        "demand-response eligibility — CKKS logistic regression + in-circuit aggregates");
    niobium::compiler().set_build_info(__FILE__, __LINE__, __TIMESTAMP__);
    niobium::Compiler::CacheParameters params;
    params.push_back({"workload", "demand_response_eligibility"});
    params.push_back({"mode", mode == Mode::SIM ? "sim" : "fog"});
    niobium::compiler().cache_parameters(params);

    niobium::compiler().capture_crypto_context(cc);
    niobium::compiler().tag_input("ct_x", ct_x);
    // tag every hand-built plaintext operand BEFORE start() (recorder caveat).
    niobium::compiler().tag_input("w_hourly", pts.w_hourly);
    niobium::compiler().tag_input("w_total_vec", pts.w_total_vec);
    niobium::compiler().tag_input("w_peak_vec", pts.w_peak_vec);
    niobium::compiler().tag_input("bias_vec", pts.bias_vec);
    niobium::compiler().tag_input("mask_slot0", pts.mask_slot0);
    niobium::compiler().tag_keys(cc);

    Ciphertext<DCRTPoly> ct_openfhe;
    if (!niobium::compiler().is_cache_valid()) {
        niobium::compiler().start();
        auto prob = run_circuit(cc, model, pts, ct_x);
        niobium::compiler().probe("prob", prob);
        niobium::compiler().stop();
        ct_openfhe = prob;   // stash for the ring-level differential
    }

    if (!niobium::compiler().replay()) {
        std::cerr << "[ERROR] replay failed" << std::endl;
        return 1;
    }

    Ciphertext<DCRTPoly> ct_result;
    if (!niobium::compiler().result(cc, "prob", ct_result)) {
        std::cerr << "[ERROR] could not retrieve result" << std::endl;
        return 1;
    }

    // ---- free ring-level identity check: simulator vs OpenFHE --------------
    if (ct_openfhe) {
        const auto& oe = ct_openfhe->GetElements();
        const auto& sm = ct_result->GetElements();
        bool identical = (oe.size() == sm.size());
        size_t total_diffs = 0;
        for (size_t c = 0; identical && c < oe.size(); ++c) {
            const auto& ot = oe[c].GetAllElements();
            const auto& st = sm[c].GetAllElements();
            if (ot.size() != st.size()) { identical = false; break; }
            for (size_t t = 0; t < ot.size(); ++t) {
                const auto& ov = ot[t].GetValues();
                const auto& sv = st[t].GetValues();
                for (size_t i = 0; i < ov.GetLength(); ++i)
                    if (ov[i] != sv[i]) ++total_diffs;
            }
        }
        std::cout << "ring-level simulator-vs-OpenFHE: "
                  << (identical && total_diffs == 0 ? "BIT-IDENTICAL"
                                                    : "DIVERGE (" + std::to_string(total_diffs) + " coeffs)")
                  << std::endl;
    }

    if (!Serial::SerializeToFile(home + "/ct_result.bin", ct_result, SerType::BINARY))
        throw std::runtime_error("serialize result failed");
    std::cout << "returned " << fs::file_size(home + "/ct_result.bin")
              << " bytes (still encrypted) -> ct_result.bin" << std::endl;
    return 0;
}
